
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.entities;

import com.citrix.sharefile.api.SFApiClient;
import com.citrix.sharefile.api.SFApiQuery;
import com.citrix.sharefile.api.interfaces.ISFApiClient;
import com.citrix.sharefile.api.interfaces.ISFQuery;
import com.citrix.sharefile.api.models.SFFileLock;

import java.net.URI;

public class SFFileLockEntity extends SFODataEntityBase
{
    public SFFileLockEntity(ISFApiClient apiClient)
    {
        super(apiClient);
    }

    /**
	* Get Item Lock info
	* Retrieves the lock info for a given Item.
	* @param url 	
	* @return Lock info
    */
	public ISFQuery<SFFileLock> getByItem(URI url)
	{
		SFApiQuery<SFFileLock> sfApiQuery = new SFApiQuery<SFFileLock>(this.apiClient);
		sfApiQuery.setFrom("Items");
		sfApiQuery.setAction("FileLock");
		sfApiQuery.addIds(url);
		sfApiQuery.setHttpMethod("GET");
		return sfApiQuery;
	}

    /**
	* Create Lock
	* @param url 	
	* @param fileLock 	
	* @return The created item Lock object
    */
	public ISFQuery<SFFileLock> createByItem(URI url, SFFileLock fileLock)
	{
		SFApiQuery<SFFileLock> sfApiQuery = new SFApiQuery<SFFileLock>(this.apiClient);
		sfApiQuery.setFrom("Items");
		sfApiQuery.setAction("FileLock");
		sfApiQuery.addIds(url);
		sfApiQuery.setBody(fileLock);
		sfApiQuery.setHttpMethod("POST");
		return sfApiQuery;
	}

    /**
	* Update FileLock
    * {
    * LockId:"lockid",
    * Owner:{Id:"ownerid"},
    * ExpirationTimeInMinutes:30
    * }
	* @param url 	
	* @param fileLock 	
	* @return The updated lock object
    */
	public ISFQuery<SFFileLock> updateByItem(URI url, SFFileLock fileLock)
	{
		SFApiQuery<SFFileLock> sfApiQuery = new SFApiQuery<SFFileLock>(this.apiClient);
		sfApiQuery.setFrom("Items");
		sfApiQuery.setAction("FileLock");
		sfApiQuery.addIds(url);
		sfApiQuery.setBody(fileLock);
		sfApiQuery.setHttpMethod("PATCH");
		return sfApiQuery;
	}

    /**
	* Unlock File
	* Unlock a locked file.
	* @param url 	
	* @param lockid 	
    */
	public ISFQuery deleteByItem(URI url, String lockid)
	{
		SFApiQuery sfApiQuery = new SFApiQuery(this.apiClient);
		sfApiQuery.setFrom("Items");
		sfApiQuery.setAction("FileLock");
		sfApiQuery.addIds(url);
		sfApiQuery.addActionIds(lockid);
		sfApiQuery.setHttpMethod("DELETE");
		return sfApiQuery;
	}

}

