
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2015 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.internal.entities;

import com.sharefile.api.*;
import com.sharefile.api.entities.*;
import com.sharefile.api.models.*;
import com.sharefile.api.internal.models.*;
import com.sharefile.api.SFApiQuery;
import com.sharefile.api.interfaces.ISFQuery;


import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
 
import com.google.gson.annotations.SerializedName;
import com.sharefile.api.enumerations.SFSafeEnum;
import com.sharefile.api.enumerations.SFSafeEnumFlags;

public class SFNotificationsEntityInternal extends SFODataEntityBase
{
	public SFNotificationsEntityInternal(ISFApiClient client) {
		super(client);
	}

	public ISFQuery failedShare(String id, String email, String eventType) throws InvalidOrMissingParameterException 	{
		if (id == null) {
			throw new InvalidOrMissingParameterException("id");
		}
		if (email == null) {
			throw new InvalidOrMissingParameterException("email");
		}
		if (eventType == null) {
			throw new InvalidOrMissingParameterException("eventType");
		}

		SFApiQuery sfApiQuery = new SFApiQuery(this.client);
		sfApiQuery.setFrom("Notifications");
		sfApiQuery.setAction("FailedShare");
		sfApiQuery.addActionIds(id);
		sfApiQuery.addQueryString("email", email);
		sfApiQuery.addQueryString("eventType", eventType);
		sfApiQuery.setHttpMethod("POST");
		return sfApiQuery;
	}

	public ISFQuery failedWelcome(String id, String email, String eventType) throws InvalidOrMissingParameterException 	{
		if (id == null) {
			throw new InvalidOrMissingParameterException("id");
		}
		if (email == null) {
			throw new InvalidOrMissingParameterException("email");
		}
		if (eventType == null) {
			throw new InvalidOrMissingParameterException("eventType");
		}

		SFApiQuery sfApiQuery = new SFApiQuery(this.client);
		sfApiQuery.setFrom("Notifications");
		sfApiQuery.setAction("FailedWelcome");
		sfApiQuery.addActionIds(id);
		sfApiQuery.addQueryString("email", email);
		sfApiQuery.addQueryString("eventType", eventType);
		sfApiQuery.setHttpMethod("POST");
		return sfApiQuery;
	}

}

