
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2015 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.sharefile.api.*;
import com.sharefile.api.enumerations.*;
import com.sharefile.api.models.*;

public class SFAccountUser extends SFUser {

	@SerializedName("IsAdministrator")
	private Boolean IsAdministrator;
	@SerializedName("CanCreateFolders")
	private Boolean CanCreateFolders;
	@SerializedName("CanUseFileBox")
	private Boolean CanUseFileBox;
	@SerializedName("CanManageUsers")
	private Boolean CanManageUsers;
	@SerializedName("IsVirtualClient")
	private Boolean IsVirtualClient;
	@SerializedName("DiskSpace")
	private Integer DiskSpace;
	@SerializedName("Bandwidth")
	private Integer Bandwidth;
	@SerializedName("StorageQuotaLimitGB")
	private Integer StorageQuotaLimitGB;
	@SerializedName("StorageQuotaPercent")
	private Integer StorageQuotaPercent;
	@SerializedName("EnableHardLimit")
	private Boolean EnableHardLimit;

	public Boolean getIsAdministrator() {
		return this.IsAdministrator;
	}

	public void setIsAdministrator(Boolean isadministrator) {
		this.IsAdministrator = isadministrator;
	}
	public Boolean getCanCreateFolders() {
		return this.CanCreateFolders;
	}

	public void setCanCreateFolders(Boolean cancreatefolders) {
		this.CanCreateFolders = cancreatefolders;
	}
	public Boolean getCanUseFileBox() {
		return this.CanUseFileBox;
	}

	public void setCanUseFileBox(Boolean canusefilebox) {
		this.CanUseFileBox = canusefilebox;
	}
	public Boolean getCanManageUsers() {
		return this.CanManageUsers;
	}

	public void setCanManageUsers(Boolean canmanageusers) {
		this.CanManageUsers = canmanageusers;
	}
	public Boolean getIsVirtualClient() {
		return this.IsVirtualClient;
	}

	public void setIsVirtualClient(Boolean isvirtualclient) {
		this.IsVirtualClient = isvirtualclient;
	}
	public Integer getDiskSpace() {
		return this.DiskSpace;
	}

	public void setDiskSpace(Integer diskspace) {
		this.DiskSpace = diskspace;
	}
	public Integer getBandwidth() {
		return this.Bandwidth;
	}

	public void setBandwidth(Integer bandwidth) {
		this.Bandwidth = bandwidth;
	}
	public Integer getStorageQuotaLimitGB() {
		return this.StorageQuotaLimitGB;
	}

	public void setStorageQuotaLimitGB(Integer storagequotalimitgb) {
		this.StorageQuotaLimitGB = storagequotalimitgb;
	}
	public Integer getStorageQuotaPercent() {
		return this.StorageQuotaPercent;
	}

	public void setStorageQuotaPercent(Integer storagequotapercent) {
		this.StorageQuotaPercent = storagequotapercent;
	}
	public Boolean getEnableHardLimit() {
		return this.EnableHardLimit;
	}

	public void setEnableHardLimit(Boolean enablehardlimit) {
		this.EnableHardLimit = enablehardlimit;
	}

}