
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.entities;

import java.util.ArrayList;

import com.sharefile.api.SFApiQuery;
import com.sharefile.api.enumerations.SFHttpMethod;
import com.sharefile.api.models.SFContact;
import com.sharefile.api.models.SFGroup;
import com.sharefile.api.models.SFODataFeed;


public class SFGroupsEntity extends SFODataEntityBase
{
    /**
	* Get Group List
	* Retrieves all Distribution Groups this user has permissions to View in this account
	* @return a list of Groups this user has access to
    */
	public SFApiQuery<SFODataFeed<SFGroup>> get()
	{
		SFApiQuery<SFODataFeed<SFGroup>> query = new SFApiQuery<SFODataFeed<SFGroup>>();
		query.setFrom("Groups");
		query.setHttpMethod(SFHttpMethod.GET);
		return query;
	}

    /**
	* Get Group List
	* Retrieves all Distribution Groups this user has permissions to View in this account
	* @return a list of Groups this user has access to
    */
	public SFApiQuery<SFGroup> get(String id)
	{
		SFApiQuery<SFGroup> query = new SFApiQuery<SFGroup>();
		query.setFrom("Groups");
		query.setId(id);
		query.setHttpMethod(SFHttpMethod.GET);
		return query;
	}

    /**
	* Delete Group
	* Removes a single Group by id
	* @param id 	
    */
	public SFApiQuery delete(String id)
	{
		SFApiQuery query = new SFApiQuery();
		query.setFrom("Groups");
		query.setId(id);
		query.setHttpMethod(SFHttpMethod.DELETE);
		return query;
	}

    /**
	* Create Group
    * {
    * "Name":"Name",
    * "IsShared":true,
    * "Contacts":[{"Email":"user.one@domain.com"},{"Email":"user.two@domain.com"}]
    * }
	* Creates a new group. The Post body must include the specification of the group.
	* @param group 	
	* @return the new group instance
    */
	public SFApiQuery<SFGroup> create(String id , SFGroup group)
	{
		SFApiQuery<SFGroup> query = new SFApiQuery<SFGroup>();
		query.setFrom("Groups");
		query.setId(id);
		query.setBody(group);
		query.setHttpMethod(SFHttpMethod.POST);
		return query;
	}

    /**
	* Update Group
    * {
    * "Name":"Name",
    * "IsShared":true,
    * }
	* Updates an existing group.
	* This operation will ignore the provided clients list. Use the \Contacts navigation link to
	* add/remove elements from a group
	* @param id 	
	* @param group 	
	* @return the modified group object
    */
	public SFApiQuery<SFGroup> update(String id, SFGroup group)
	{
		SFApiQuery<SFGroup> query = new SFApiQuery<SFGroup>();
		query.setFrom("Groups");
		query.setId(id);
		query.setBody(group);
		query.setHttpMethod(SFHttpMethod.PATCH);
		return query;
	}

    /**
	* Get Group Contacts
	* Retrieves the Contacts navigation property of a Group
	* @param id 	
	* @return A feed of Contacts representing the members of the Group
    */
	public SFApiQuery<SFODataFeed<SFContact>> getContacts(String id)
	{
		SFApiQuery<SFODataFeed<SFContact>> query = new SFApiQuery<SFODataFeed<SFContact>>();
		query.setFrom("Groups");
		query.setAction("Contacts");
		query.setId(id);
		query.setHttpMethod(SFHttpMethod.GET);
		return query;
	}

    /**
	* Add Contacts to Group
    * [{"Email":"user.one@domain.com"},{"Id":"abcd"}]
	* Adds a list of contacts to a group
	* The contact list may contain either contact ID (same as User ID) or Email.
	* @param id 	
	* @param contacts 	
	* @return The updated list of contacts for this group
    */
	public SFApiQuery<SFODataFeed<SFContact>> createContacts(String id, ArrayList<SFContact> contacts)
	{
		SFApiQuery<SFODataFeed<SFContact>> query = new SFApiQuery<SFODataFeed<SFContact>>();
		query.setFrom("Groups");
		query.setAction("Contacts");
		query.setId(id);
		query.setBody(contacts);
		query.setHttpMethod(SFHttpMethod.POST);
		return query;
	}

    /**
	* Remove Contacts from Group
    * [{"Email":"user.one@domain.com"},{"Id":"abcd"}]
	* Removes contacts from a group
	* The contact list may contain either contact ID (same as User ID) or Email.
	* This method will ignore missing references in the provided list - i.e., if an email in the contacts
	* list is not present in the group, it will be ignored.
	* The method will not enforce that ID and Email match inside a single Contact instance: Id will be
	* looked up first, then Email.
	* @param id 	
	* @param contacts 	
	* @return The updated list of contacts for this group
    */
	public SFApiQuery<SFODataFeed<SFContact>> deleteContacts(String id, ArrayList<SFContact> contacts)
	{
		SFApiQuery<SFODataFeed<SFContact>> query = new SFApiQuery<SFODataFeed<SFContact>>();
		query.setFrom("Groups");
		query.setAction("Contacts");
		query.setId(id);
		query.setBody(contacts);
		query.setHttpMethod(SFHttpMethod.DELETE);
		return query;
	}

}

