
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

public class SFEnsSubscriberConfiguration extends SFODataObject {

	private Boolean mIsEnsEnabled;
	private String mEnsServerUrl;
	private String mVersion;
	private Object mRecommendedSyncInterval;

	public Boolean getIsEnsEnabled() {
		return mIsEnsEnabled;
	}

	public void setIsEnsEnabled(Boolean isensenabled) {
		mIsEnsEnabled = isensenabled;
	}
	public String getEnsServerUrl() {
		return mEnsServerUrl;
	}

	public void setEnsServerUrl(String ensserverurl) {
		mEnsServerUrl = ensserverurl;
	}
	public String getVersion() {
		return mVersion;
	}

	public void setVersion(String version) {
		mVersion = version;
	}
	public Object getRecommendedSyncInterval() {
		return mRecommendedSyncInterval;
	}

	public void setRecommendedSyncInterval(Object recommendedsyncinterval) {
		mRecommendedSyncInterval = recommendedsyncinterval;
	}
}