
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2016 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.*;
import com.citrix.sharefile.api.enumerations.*;
import com.citrix.sharefile.api.models.*;

public class SFAccessControlsCloneParams extends SFODataObject {

	@SerializedName("NotifyUser")
	private Boolean NotifyUser;
	@SerializedName("NotifyMessage")
	private String NotifyMessage;
	@SerializedName("FolderId")
	private String FolderId;
	@SerializedName("UserId")
	private String UserId;
	@SerializedName("CloneUserIds")
	private ArrayList<String> CloneUserIds;

		/**
		* Defines whether the cloned users should receieve a notice on the permission grant.
		*/
	public Boolean getNotifyUser() {
		return this.NotifyUser;
	}

		/**
		* Defines whether the cloned users should receieve a notice on the permission grant.
		*/
	public void setNotifyUser(Boolean notifyuser) {
		this.NotifyUser = notifyuser;
	}
		/**
		* Custom notification message, if any.
		*/
	public String getNotifyMessage() {
		return this.NotifyMessage;
	}

		/**
		* Custom notification message, if any.
		*/
	public void setNotifyMessage(String notifymessage) {
		this.NotifyMessage = notifymessage;
	}
		/**
		* The source user's permissions for this folder and all subdirectories
		* will be copied into the cloned users.
		*/
	public String getFolderId() {
		return this.FolderId;
	}

		/**
		* The source user's permissions for this folder and all subdirectories
		* will be copied into the cloned users.
		*/
	public void setFolderId(String folderid) {
		this.FolderId = folderid;
	}
		/**
		* This user's permissions will be used as the source for all cloned users.
		*/
	public String getUserId() {
		return this.UserId;
	}

		/**
		* This user's permissions will be used as the source for all cloned users.
		*/
	public void setUserId(String userid) {
		this.UserId = userid;
	}
		/**
		* List of existing users that will receive cloned permissions.
		*/
	public ArrayList<String> getCloneUserIds() {
		return this.CloneUserIds;
	}

		/**
		* List of existing users that will receive cloned permissions.
		*/
	public void setCloneUserIds(ArrayList<String> cloneuserids) {
		this.CloneUserIds = cloneuserids;
	}

}