
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.*;
import com.citrix.sharefile.api.enumerations.*;
import com.citrix.sharefile.api.models.*;

public class SFAccountStatus extends SFODataObject {

	@SerializedName("IsLockedForMaintenance")
	private Boolean IsLockedForMaintenance;
	@SerializedName("LockedForMaintenanceDate")
	private Date LockedForMaintenanceDate;
	@SerializedName("Database")
	private String Database;
	@SerializedName("Subdomains")
	private ArrayList<String> Subdomains;
	@SerializedName("TopLevelDomain")
	private String TopLevelDomain;
	@SerializedName("APITopLevelDomain")
	private String APITopLevelDomain;

		/**
		* If true, indicates account is currently unavailable due to maintenance
		*/
	public Boolean getIsLockedForMaintenance() {
		return this.IsLockedForMaintenance;
	}

		/**
		* If true, indicates account is currently unavailable due to maintenance
		*/
	public void setIsLockedForMaintenance(Boolean islockedformaintenance) {
		this.IsLockedForMaintenance = islockedformaintenance;
	}
		/**
		* Time account entered maintenance mode
		*/
	public Date getLockedForMaintenanceDate() {
		return this.LockedForMaintenanceDate;
	}

		/**
		* Time account entered maintenance mode
		*/
	public void setLockedForMaintenanceDate(Date lockedformaintenancedate) {
		this.LockedForMaintenanceDate = lockedformaintenancedate;
	}
		/**
		* Account's primary DB
		*/
	public String getDatabase() {
		return this.Database;
	}

		/**
		* Account's primary DB
		*/
	public void setDatabase(String database) {
		this.Database = database;
	}
		/**
		* Account's subdomains
		*/
	public ArrayList<String> getSubdomains() {
		return this.Subdomains;
	}

		/**
		* Account's subdomains
		*/
	public void setSubdomains(ArrayList<String> subdomains) {
		this.Subdomains = subdomains;
	}
		/**
		* Account's website domain (eg, sharefile.eu)
		*/
	public String getTopLevelDomain() {
		return this.TopLevelDomain;
	}

		/**
		* Account's website domain (eg, sharefile.eu)
		*/
	public void setTopLevelDomain(String topleveldomain) {
		this.TopLevelDomain = topleveldomain;
	}
		/**
		* Account's api domain (eg, sf-api.edu)
		*/
	public String getAPITopLevelDomain() {
		return this.APITopLevelDomain;
	}

		/**
		* Account's api domain (eg, sf-api.edu)
		*/
	public void setAPITopLevelDomain(String apitopleveldomain) {
		this.APITopLevelDomain = apitopleveldomain;
	}

}