
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.*;
import com.citrix.sharefile.api.enumerations.*;
import com.citrix.sharefile.api.models.*;

public class SFCapability extends SFODataObject {

	@SerializedName("Name")
	private SFSafeEnum<SFCapabilityName> Name;
	@SerializedName("Version")
	private String Version;
	@SerializedName("ScopedHostsAndProviders")
	private ArrayList<String> ScopedHostsAndProviders;
	@SerializedName("SupportedDataTypes")
	private ArrayList<String> SupportedDataTypes;

	public SFSafeEnum<SFCapabilityName> getName() {
		return this.Name;
	}

	public void setName(SFSafeEnum<SFCapabilityName> name) {
		this.Name = name;
	}
	public String getVersion() {
		return this.Version;
	}

	public void setVersion(String version) {
		this.Version = version;
	}
		/**
		* Indicates the list of hosts and providers with which the associated capability can operate.
		* There are two known constants that offer a convenient way to refer to the current provider (self) and ShareFile (sf)
		* Otherwise, values will be prefixed with https protocol.
		*/
	public ArrayList<String> getScopedHostsAndProviders() {
		return this.ScopedHostsAndProviders;
	}

		/**
		* Indicates the list of hosts and providers with which the associated capability can operate.
		* There are two known constants that offer a convenient way to refer to the current provider (self) and ShareFile (sf)
		* Otherwise, values will be prefixed with https protocol.
		*/
	public void setScopedHostsAndProviders(ArrayList<String> scopedhostsandproviders) {
		this.ScopedHostsAndProviders = scopedhostsandproviders;
	}
		/**
		* Indicates the data types are supported based on this capability. If there are no restrictions, this value will be empty or null.
		* For backwards compatibility, for an empty list will imply only Folders are supported.
		*/
	public ArrayList<String> getSupportedDataTypes() {
		return this.SupportedDataTypes;
	}

		/**
		* Indicates the data types are supported based on this capability. If there are no restrictions, this value will be empty or null.
		* For backwards compatibility, for an empty list will imply only Folders are supported.
		*/
	public void setSupportedDataTypes(ArrayList<String> supporteddatatypes) {
		this.SupportedDataTypes = supporteddatatypes;
	}

}