
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.*;
import com.citrix.sharefile.api.enumerations.*;
import com.citrix.sharefile.api.models.*;

public class SFClickTrailSession extends SFODataObject {

	@SerializedName("AccountId")
	private String AccountId;
	@SerializedName("User")
	private SFUser User;
	@SerializedName("Browser")
	private String Browser;
	@SerializedName("IPAddress")
	private String IPAddress;
	@SerializedName("City")
	private String City;
	@SerializedName("Country")
	private String Country;
	@SerializedName("StartTime")
	private Date StartTime;
	@SerializedName("EndTime")
	private Date EndTime;
	@SerializedName("Events")
	private ArrayList<SFClickTrailEvent> Events;

	public String getAccountId() {
		return this.AccountId;
	}

	public void setAccountId(String accountid) {
		this.AccountId = accountid;
	}
	public SFUser getUser() {
		return this.User;
	}

	public void setUser(SFUser user) {
		this.User = user;
	}
	public String getBrowser() {
		return this.Browser;
	}

	public void setBrowser(String browser) {
		this.Browser = browser;
	}
	public String getIPAddress() {
		return this.IPAddress;
	}

	public void setIPAddress(String ipaddress) {
		this.IPAddress = ipaddress;
	}
	public String getCity() {
		return this.City;
	}

	public void setCity(String city) {
		this.City = city;
	}
	public String getCountry() {
		return this.Country;
	}

	public void setCountry(String country) {
		this.Country = country;
	}
	public Date getStartTime() {
		return this.StartTime;
	}

	public void setStartTime(Date starttime) {
		this.StartTime = starttime;
	}
	public Date getEndTime() {
		return this.EndTime;
	}

	public void setEndTime(Date endtime) {
		this.EndTime = endtime;
	}
	public ArrayList<SFClickTrailEvent> getEvents() {
		return this.Events;
	}

	public void setEvents(ArrayList<SFClickTrailEvent> events) {
		this.Events = events;
	}

}