
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.*;
import com.citrix.sharefile.api.enumerations.*;
import com.citrix.sharefile.api.models.*;

public class SFDeletedAccount extends SFODataObject {

	@SerializedName("S3ActivityLogDeletionQueueDate")
	private Date S3ActivityLogDeletionQueueDate;
	@SerializedName("S3ActivityLogDeletionDate")
	private Date S3ActivityLogDeletionDate;

		/**
		* Indicates date when S3 deletion job was queued.
		*/
	public Date getS3ActivityLogDeletionQueueDate() {
		return this.S3ActivityLogDeletionQueueDate;
	}

		/**
		* Indicates date when S3 deletion job was queued.
		*/
	public void setS3ActivityLogDeletionQueueDate(Date s3activitylogdeletionqueuedate) {
		this.S3ActivityLogDeletionQueueDate = s3activitylogdeletionqueuedate;
	}
		/**
		* Indicates date when S3 deletion job was completed.
		*/
	public Date getS3ActivityLogDeletionDate() {
		return this.S3ActivityLogDeletionDate;
	}

		/**
		* Indicates date when S3 deletion job was completed.
		*/
	public void setS3ActivityLogDeletionDate(Date s3activitylogdeletiondate) {
		this.S3ActivityLogDeletionDate = s3activitylogdeletiondate;
	}

}