
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.enumerations.SFSafeEnum;
import com.citrix.sharefile.api.models.*;

public class SFFreeTrialAccount extends SFAccount {

	@SerializedName("PromoCode")
	private String PromoCode;
	@SerializedName("EndDate")
	private Date EndDate;
	@SerializedName("IsValid")
	private Boolean IsValid;
	@SerializedName("ConversionType")
	private String ConversionType;
	@SerializedName("HasFollowedUp")
	private Boolean HasFollowedUp;
	@SerializedName("FollowUpDate")
	private Date FollowUpDate;
	@SerializedName("CancellationReason")
	private String CancellationReason;
	@SerializedName("SignupProcess")
	private String SignupProcess;
	@SerializedName("ConversionIndexDay7")
	private Double ConversionIndexDay7;
	@SerializedName("ConversionIndexDay14")
	private Double ConversionIndexDay14;
	@SerializedName("LTVIndex")
	private Double LTVIndex;
	@SerializedName("AllSources")
	private String AllSources;
	@SerializedName("ReferralID")
	private String ReferralID;
	@SerializedName("TrialTypeID")
	private Integer TrialTypeID;
	@SerializedName("InitialCallRepID")
	private String InitialCallRepID;
	@SerializedName("InitialCallDate")
	private Date InitialCallDate;
	@SerializedName("DemoStatus")
	private Integer DemoStatus;
	@SerializedName("DemoDate")
	private Date DemoDate;
	@SerializedName("MarketoID")
	private String MarketoID;

	public String getPromoCode() {
		return this.PromoCode;
	}

	public void setPromoCode(String promocode) {
		this.PromoCode = promocode;
	}
	public Date getEndDate() {
		return this.EndDate;
	}

	public void setEndDate(Date enddate) {
		this.EndDate = enddate;
	}
	public Boolean getIsValid() {
		return this.IsValid;
	}

	public void setIsValid(Boolean isvalid) {
		this.IsValid = isvalid;
	}
	public String getConversionType() {
		return this.ConversionType;
	}

	public void setConversionType(String conversiontype) {
		this.ConversionType = conversiontype;
	}
	public Boolean getHasFollowedUp() {
		return this.HasFollowedUp;
	}

	public void setHasFollowedUp(Boolean hasfollowedup) {
		this.HasFollowedUp = hasfollowedup;
	}
	public Date getFollowUpDate() {
		return this.FollowUpDate;
	}

	public void setFollowUpDate(Date followupdate) {
		this.FollowUpDate = followupdate;
	}
	public String getCancellationReason() {
		return this.CancellationReason;
	}

	public void setCancellationReason(String cancellationreason) {
		this.CancellationReason = cancellationreason;
	}
	public String getSignupProcess() {
		return this.SignupProcess;
	}

	public void setSignupProcess(String signupprocess) {
		this.SignupProcess = signupprocess;
	}
	public Double getConversionIndexDay7() {
		return this.ConversionIndexDay7;
	}

	public void setConversionIndexDay7(Double conversionindexday7) {
		this.ConversionIndexDay7 = conversionindexday7;
	}
	public Double getConversionIndexDay14() {
		return this.ConversionIndexDay14;
	}

	public void setConversionIndexDay14(Double conversionindexday14) {
		this.ConversionIndexDay14 = conversionindexday14;
	}
	public Double getLTVIndex() {
		return this.LTVIndex;
	}

	public void setLTVIndex(Double ltvindex) {
		this.LTVIndex = ltvindex;
	}
	public String getAllSources() {
		return this.AllSources;
	}

	public void setAllSources(String allsources) {
		this.AllSources = allsources;
	}
	public String getReferralID() {
		return this.ReferralID;
	}

	public void setReferralID(String referralid) {
		this.ReferralID = referralid;
	}
	public Integer getTrialTypeID() {
		return this.TrialTypeID;
	}

	public void setTrialTypeID(Integer trialtypeid) {
		this.TrialTypeID = trialtypeid;
	}
	public String getInitialCallRepID() {
		return this.InitialCallRepID;
	}

	public void setInitialCallRepID(String initialcallrepid) {
		this.InitialCallRepID = initialcallrepid;
	}
	public Date getInitialCallDate() {
		return this.InitialCallDate;
	}

	public void setInitialCallDate(Date initialcalldate) {
		this.InitialCallDate = initialcalldate;
	}
	public Integer getDemoStatus() {
		return this.DemoStatus;
	}

	public void setDemoStatus(Integer demostatus) {
		this.DemoStatus = demostatus;
	}
	public Date getDemoDate() {
		return this.DemoDate;
	}

	public void setDemoDate(Date demodate) {
		this.DemoDate = demodate;
	}
	public String getMarketoID() {
		return this.MarketoID;
	}

	public void setMarketoID(String marketoid) {
		this.MarketoID = marketoid;
	}

}