
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2016 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.*;
import com.citrix.sharefile.api.enumerations.*;
import com.citrix.sharefile.api.models.*;

public class SFIrmClassification extends SFODataObject {

	@SerializedName("Name")
	private String Name;
	@SerializedName("Description")
	private String Description;
	@SerializedName("PrimaryAccessRightParams")
	private SFIrmPrimaryAccessRightParams PrimaryAccessRightParams;
	@SerializedName("IsEnabled")
	private Boolean IsEnabled;
	@SerializedName("NumberOfProtectionDays")
	private Integer NumberOfProtectionDays;

		/**
		* Name of the Irm Classification
		*/
	public String getName() {
		return this.Name;
	}

		/**
		* Name of the Irm Classification
		*/
	public void setName(String name) {
		this.Name = name;
	}
		/**
		* Description of the Irm Classification if any
		*/
	public String getDescription() {
		return this.Description;
	}

		/**
		* Description of the Irm Classification if any
		*/
	public void setDescription(String description) {
		this.Description = description;
	}
		/**
		* AccessRight permissions on an IRM Classification
		*/
	public SFIrmPrimaryAccessRightParams getPrimaryAccessRightParams() {
		return this.PrimaryAccessRightParams;
	}

		/**
		* AccessRight permissions on an IRM Classification
		*/
	public void setPrimaryAccessRightParams(SFIrmPrimaryAccessRightParams primaryaccessrightparams) {
		this.PrimaryAccessRightParams = primaryaccessrightparams;
	}
		/**
		* Use this flag to enable/ disable the Irm Classification.
		* If disabled, this Irm Classification won't show up in the List of active IrmClassifications on an account.
		*/
	public Boolean getIsEnabled() {
		return this.IsEnabled;
	}

		/**
		* Use this flag to enable/ disable the Irm Classification.
		* If disabled, this Irm Classification won't show up in the List of active IrmClassifications on an account.
		*/
	public void setIsEnabled(Boolean isenabled) {
		this.IsEnabled = isenabled;
	}
		/**
		* Defines the numner of days after which the user won't be access the documents protected with this classification.
		*/
	public Integer getNumberOfProtectionDays() {
		return this.NumberOfProtectionDays;
	}

		/**
		* Defines the numner of days after which the user won't be access the documents protected with this classification.
		*/
	public void setNumberOfProtectionDays(Integer numberofprotectiondays) {
		this.NumberOfProtectionDays = numberofprotectiondays;
	}

}