
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2016 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;
 
import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.enumerations.SFSafeEnum;
import com.citrix.sharefile.api.enumerations.SFSafeEnumFlags;

public enum SFItemAction {
	Download,
	Upload,
	View,
	WatermarkDownload,
	Note,
	Url,
	DownloadESignature,
	WOPI_View,
	WOPI_Download,
	UploadReceipt,
	FileLock,
	FileUnLock,
	FileDiscardLock,
	None,
	ZipUpload,
	Item_Delete,
	Item_Edit,
	Item_Restore,
	Move,
	NewFolder,
	NewNote,
	NewLink,
	StreamLockCreate,
	StreamLockDelete,
	StreamLockUpdate,
	StreamLockRelease,
	DLP_Scan_Accept,
	DLP_Scan_Reject,
	DLP_Share_Allow,
	DLP_Share_Deny,
	Document_View,
	Document_Edit,
	Item_Archive
}