
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2015 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.*;
import com.citrix.sharefile.api.enumerations.*;
import com.citrix.sharefile.api.models.*;

public class SFNotifyUsersParams extends SFODataObject {

	@SerializedName("UserIds")
	private ArrayList<String> UserIds;
	@SerializedName("CustomMessage")
	private String CustomMessage;

	public ArrayList<String> getUserIds() {
		return this.UserIds;
	}

	public void setUserIds(ArrayList<String> userids) {
		this.UserIds = userids;
	}
	public String getCustomMessage() {
		return this.CustomMessage;
	}

	public void setCustomMessage(String custommessage) {
		this.CustomMessage = custommessage;
	}

}