
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;
 
import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.enumerations.SFSafeEnum;
import com.citrix.sharefile.api.enumerations.SFSafeEnumFlags;

public enum SFRepRole {
	AccountManager,
	AccountServices,
	Branding,
	CustomerSupport,
	HR,
	Impersonation,
	InsideSales,
	InternBranding,
	InternDeveloper,
	MasterAccountManager,
	MasterBranding,
	MasterDeveloper,
	MasterSales,
	OutboundSales,
	Sales,
	SeniorAccountManager,
	SuccessManager,
	InternalAppsDev,
	SupportManager,
	LevelISupport,
	LevelIISupport,
	LevelIIISupport,
	Engineering,
	Manager,
	SalesDirector,
	InboundSalesManager,
	OutboundSalesManager,
	Accounting,
	ResellersManager,
	TeamImpersonation,
	ClientServicesManager,
	BrandingManager,
	OLMktg,
	ExecTeam,
	Other,
	LoginAsSupport,
	EnterpriseSalesmanager,
	SSO,
	ProjectManager,
	QA,
	TrialDispatcher,
	TrialDispatcherVerticals,
	ReadOnly,
	AccountManagerAutoAssign,
	AccountProvisioning,
	CanDeleteAccounts,
	SupportTriage,
	OutboundCustomerCare,
	SalesEngineer,
	Release,
	TechnicalServiceEngineer,
	IT,
	Database,
	BillingAdmin,
	SalesOps,
	OAuthClientKeyAdmin,
	EditMasterAdmin
}