
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2016 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.*;
import com.citrix.sharefile.api.enumerations.*;
import com.citrix.sharefile.api.models.*;

public class SFSearchQuery extends SFODataObject {

	@SerializedName("Query")
	private SFQuery Query;
	@SerializedName("Paging")
	private SFQueryPaging Paging;
	@SerializedName("Sort")
	private SFQuerySorting Sort;
	@SerializedName("TimeoutInSeconds")
	private Integer TimeoutInSeconds;

		/**
		* Information about the query to run
		*/
	public SFQuery getQuery() {
		return this.Query;
	}

		/**
		* Information about the query to run
		*/
	public void setQuery(SFQuery query) {
		this.Query = query;
	}
		/**
		* Paging info about the search results
		*/
	public SFQueryPaging getPaging() {
		return this.Paging;
	}

		/**
		* Paging info about the search results
		*/
	public void setPaging(SFQueryPaging paging) {
		this.Paging = paging;
	}
		/**
		* How the search results should be sorted
		*/
	public SFQuerySorting getSort() {
		return this.Sort;
	}

		/**
		* How the search results should be sorted
		*/
	public void setSort(SFQuerySorting sort) {
		this.Sort = sort;
	}
		/**
		* Timeout for the search request in seconds
		*/
	public Integer getTimeoutInSeconds() {
		return this.TimeoutInSeconds;
	}

		/**
		* Timeout for the search request in seconds
		*/
	public void setTimeoutInSeconds(Integer timeoutinseconds) {
		this.TimeoutInSeconds = timeoutinseconds;
	}

}