
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.*;
import com.citrix.sharefile.api.enumerations.*;
import com.citrix.sharefile.api.models.*;

public class SFServerInfo extends SFODataObject {

	@SerializedName("MachineName")
	private String MachineName;
	@SerializedName("Directory")
	private String Directory;
	@SerializedName("Date")
	private String Date;
	@SerializedName("Tag")
	private SFServerTag Tag;

	public String getMachineName() {
		return this.MachineName;
	}

	public void setMachineName(String machinename) {
		this.MachineName = machinename;
	}
	public String getDirectory() {
		return this.Directory;
	}

	public void setDirectory(String directory) {
		this.Directory = directory;
	}
	public String getDate() {
		return this.Date;
	}

	public void setDate(String date) {
		this.Date = date;
	}
	public SFServerTag getTag() {
		return this.Tag;
	}

	public void setTag(SFServerTag tag) {
		this.Tag = tag;
	}

}