
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.*;
import com.citrix.sharefile.api.enumerations.*;
import com.citrix.sharefile.api.models.*;

public class SFSupport extends SFODataObject {

	@SerializedName("EmailAddresses")
	private ArrayList<SFEmailSupport> EmailAddresses;
	@SerializedName("PhoneNumbers")
	private ArrayList<SFPhoneSupport> PhoneNumbers;
	@SerializedName("KBUrl")
	private String KBUrl;
	@SerializedName("KBSearchUrl")
	private String KBSearchUrl;
	@SerializedName("ShowLiveChat")
	private Boolean ShowLiveChat;
	@SerializedName("ShowAccountManager")
	private Boolean ShowAccountManager;
	@SerializedName("TicketTarget")
	private String TicketTarget;
	@SerializedName("IsCustom")
	private Boolean IsCustom;
	@SerializedName("ShowFeedback")
	private Boolean ShowFeedback;

	public ArrayList<SFEmailSupport> getEmailAddresses() {
		return this.EmailAddresses;
	}

	public void setEmailAddresses(ArrayList<SFEmailSupport> emailaddresses) {
		this.EmailAddresses = emailaddresses;
	}
	public ArrayList<SFPhoneSupport> getPhoneNumbers() {
		return this.PhoneNumbers;
	}

	public void setPhoneNumbers(ArrayList<SFPhoneSupport> phonenumbers) {
		this.PhoneNumbers = phonenumbers;
	}
	public String getKBUrl() {
		return this.KBUrl;
	}

	public void setKBUrl(String kburl) {
		this.KBUrl = kburl;
	}
	public String getKBSearchUrl() {
		return this.KBSearchUrl;
	}

	public void setKBSearchUrl(String kbsearchurl) {
		this.KBSearchUrl = kbsearchurl;
	}
	public Boolean getShowLiveChat() {
		return this.ShowLiveChat;
	}

	public void setShowLiveChat(Boolean showlivechat) {
		this.ShowLiveChat = showlivechat;
	}
	public Boolean getShowAccountManager() {
		return this.ShowAccountManager;
	}

	public void setShowAccountManager(Boolean showaccountmanager) {
		this.ShowAccountManager = showaccountmanager;
	}
	public String getTicketTarget() {
		return this.TicketTarget;
	}

	public void setTicketTarget(String tickettarget) {
		this.TicketTarget = tickettarget;
	}
	public Boolean getIsCustom() {
		return this.IsCustom;
	}

	public void setIsCustom(Boolean iscustom) {
		this.IsCustom = iscustom;
	}
	public Boolean getShowFeedback() {
		return this.ShowFeedback;
	}

	public void setShowFeedback(Boolean showfeedback) {
		this.ShowFeedback = showfeedback;
	}

}