
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.*;
import com.citrix.sharefile.api.enumerations.*;
import com.citrix.sharefile.api.models.*;

public class SFUserBulkDowngradeRequest extends SFUserBulkOperationRequest {

	@SerializedName("ReassignItemsToId")
	private String ReassignItemsToId;
	@SerializedName("ReassignGroupsToId")
	private String ReassignGroupsToId;

		/**
		* If provided, all users in this bulk operation have their items reassigned to this user id
		*/
	public String getReassignItemsToId() {
		return this.ReassignItemsToId;
	}

		/**
		* If provided, all users in this bulk operation have their items reassigned to this user id
		*/
	public void setReassignItemsToId(String reassignitemstoid) {
		this.ReassignItemsToId = reassignitemstoid;
	}
		/**
		* If provided, all users in this bulk operation have their groups reassigned to this user id
		*/
	public String getReassignGroupsToId() {
		return this.ReassignGroupsToId;
	}

		/**
		* If provided, all users in this bulk operation have their groups reassigned to this user id
		*/
	public void setReassignGroupsToId(String reassigngroupstoid) {
		this.ReassignGroupsToId = reassigngroupstoid;
	}

}