
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.*;
import com.citrix.sharefile.api.enumerations.*;
import com.citrix.sharefile.api.models.*;

public class SFWorkflowBundle extends SFBundle {

	@SerializedName("WorkflowId")
	private String WorkflowId;
	@SerializedName("WorkflowType")
	private SFSafeEnum<SFWorkflowBundleType> WorkflowType;
	@SerializedName("Status")
	private SFSafeEnum<SFWorkflowBundleStatus> Status;
	@SerializedName("CompletedDate")
	private Date CompletedDate;
	@SerializedName("Initiator")
	private SFUser Initiator;
	@SerializedName("ParticipantCount")
	private Integer ParticipantCount;
	@SerializedName("Participants")
	private ArrayList<SFUser> Participants;

	public String getWorkflowId() {
		return this.WorkflowId;
	}

	public void setWorkflowId(String workflowid) {
		this.WorkflowId = workflowid;
	}
	public SFSafeEnum<SFWorkflowBundleType> getWorkflowType() {
		return this.WorkflowType;
	}

	public void setWorkflowType(SFSafeEnum<SFWorkflowBundleType> workflowtype) {
		this.WorkflowType = workflowtype;
	}
	public SFSafeEnum<SFWorkflowBundleStatus> getStatus() {
		return this.Status;
	}

	public void setStatus(SFSafeEnum<SFWorkflowBundleStatus> status) {
		this.Status = status;
	}
	public Date getCompletedDate() {
		return this.CompletedDate;
	}

	public void setCompletedDate(Date completeddate) {
		this.CompletedDate = completeddate;
	}
	public SFUser getInitiator() {
		return this.Initiator;
	}

	public void setInitiator(SFUser initiator) {
		this.Initiator = initiator;
	}
		/**
		* Total number of participants on the workflow
		*/
	public Integer getParticipantCount() {
		return this.ParticipantCount;
	}

		/**
		* Total number of participants on the workflow
		*/
	public void setParticipantCount(Integer participantcount) {
		this.ParticipantCount = participantcount;
	}
		/**
		* Collection of a short list of particpants on the workflow. Intended to be used for presentation. If an accurate count is required, use ParticipantCount.
		*/
	public ArrayList<SFUser> getParticipants() {
		return this.Participants;
	}

		/**
		* Collection of a short list of particpants on the workflow. Intended to be used for presentation. If an accurate count is required, use ParticipantCount.
		*/
	public void setParticipants(ArrayList<SFUser> participants) {
		this.Participants = participants;
	}

}