
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

import java.util.ArrayList;

public class SFDeviceWipeReport extends SFODataObject {

	private ArrayList<SFDeviceLogEntry> Logs;
	private ArrayList<SFDeviceUserWipe> WipeResults;

		/**
		* Logs
		*/
	public ArrayList<SFDeviceLogEntry> getLogs() {
		return Logs;
	}

		/**
		* Logs
		*/
	public void setLogs(ArrayList<SFDeviceLogEntry> logs) {
		Logs = logs;
	}
		/**
		* Wipe results
		*/
	public ArrayList<SFDeviceUserWipe> getWipeResults() {
		return WipeResults;
	}

		/**
		* Wipe results
		*/
	public void setWipeResults(ArrayList<SFDeviceUserWipe> wiperesults) {
		WipeResults = wiperesults;
	}
}