
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

import java.util.Date;

public class SFFavoriteFolder extends SFODataObject {

	private SFUser mUser;
	private SFItem mFolder;
	private Integer mSortOrder;
	private String mFolderAlias;
	private String mFolderName;
	private String mPath;
	private Long mFileSize;
	private Date mCreationDate;
	private String mCreatorFirstName;
	private String mCreatorLastName;

	public SFUser getUser() {
		return mUser;
	}

	public void setUser(SFUser user) {
		mUser = user;
	}
	public SFItem getFolder() {
		return mFolder;
	}

	public void setFolder(SFItem folder) {
		mFolder = folder;
	}
	public Integer getSortOrder() {
		return mSortOrder;
	}

	public void setSortOrder(Integer sortorder) {
		mSortOrder = sortorder;
	}
	public String getFolderAlias() {
		return mFolderAlias;
	}

	public void setFolderAlias(String folderalias) {
		mFolderAlias = folderalias;
	}
	public String getFolderName() {
		return mFolderName;
	}

	public void setFolderName(String foldername) {
		mFolderName = foldername;
	}
	public String getPath() {
		return mPath;
	}

	public void setPath(String path) {
		mPath = path;
	}
	public Long getFileSize() {
		return mFileSize;
	}

	public void setFileSize(Long filesize) {
		mFileSize = filesize;
	}
	public Date getCreationDate() {
		return mCreationDate;
	}

	public void setCreationDate(Date creationdate) {
		mCreationDate = creationdate;
	}
	public String getCreatorFirstName() {
		return mCreatorFirstName;
	}

	public void setCreatorFirstName(String creatorfirstname) {
		mCreatorFirstName = creatorfirstname;
	}
	public String getCreatorLastName() {
		return mCreatorLastName;
	}

	public void setCreatorLastName(String creatorlastname) {
		mCreatorLastName = creatorlastname;
	}
}