
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

public class SFFindSubdomainParams extends SFODataObject {

	private String mUsernameShort;
	private String mPassword;
	private Boolean mEmployeeOnly;

	public String getUsernameShort() {
		return mUsernameShort;
	}

	public void setUsernameShort(String usernameshort) {
		mUsernameShort = usernameshort;
	}
	public String getPassword() {
		return mPassword;
	}

	public void setPassword(String password) {
		mPassword = password;
	}
	public Boolean getEmployeeOnly() {
		return mEmployeeOnly;
	}

	public void setEmployeeOnly(Boolean employeeonly) {
		mEmployeeOnly = employeeonly;
	}
}