
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

public class SFItemInfo extends SFODataObject {

	private SFAccessControl CurrentAccessControl;
	private Boolean HasVroot = false;
	private Boolean IsSystemRoot = false;
	private Boolean IsAccountRoot = false ;
	private Boolean IsVRoot = false;
	private Boolean IsMyFolders = false;
	private Boolean IsAHomeFolder = false;
	private Boolean IsMyHomeFolder = false;
	private Boolean IsAStartFolder = false;
	private Boolean IsSharedFolder = false;
	private Boolean IsPassthrough = false;
	private Boolean IsVersioned = false;
	private Boolean CanAddFolder = false;
	private Boolean CanAddNode = false;
	private Boolean CanView = false;
	private Boolean CanDownload = false;
	private Boolean CanWatermarkDownload = false;
	private Boolean CanUpload = false;
	private Boolean CanSend = false;
	private Boolean CanDeleteCurrentItem = false;
	private Boolean CanDeleteChildItems = false;
	private Boolean CanManagePermissions = false;
	private Boolean CanEditFolderOpts = false;
	private String FolderPayID;
	private Boolean ShowFolderPayBuyButton = false;
	private SFTreeMode TreeMode;
	private Boolean TreeModeOperationAllowed = false;
	private String TreeModeSourceId;

	public SFAccessControl getCurrentAccessControl() {
		return CurrentAccessControl;
	}

	public void setCurrentAccessControl(SFAccessControl currentaccesscontrol) {
		CurrentAccessControl = currentaccesscontrol;
	}
	public Boolean getHasVroot() {
		return HasVroot;
	}

	public void setHasVroot(Boolean hasvroot) {
		HasVroot = hasvroot;
	}
	public Boolean getIsSystemRoot() {
		return IsSystemRoot;
	}

	public void setIsSystemRoot(Boolean issystemroot) {
		IsSystemRoot = issystemroot;
	}
	public Boolean getIsAccountRoot() {
		return IsAccountRoot;
	}

	public void setIsAccountRoot(Boolean isaccountroot) {
		IsAccountRoot = isaccountroot;
	}
	public Boolean getIsVRoot() {
		return IsVRoot;
	}

	public void setIsVRoot(Boolean isvroot) {
		IsVRoot = isvroot;
	}
	public Boolean getIsMyFolders() {
		return IsMyFolders;
	}

	public void setIsMyFolders(Boolean ismyfolders) {
		IsMyFolders = ismyfolders;
	}
	public Boolean getIsAHomeFolder() {
		return IsAHomeFolder;
	}

	public void setIsAHomeFolder(Boolean isahomefolder) {
		IsAHomeFolder = isahomefolder;
	}
	public Boolean getIsMyHomeFolder() {
		return IsMyHomeFolder;
	}

	public void setIsMyHomeFolder(Boolean ismyhomefolder) {
		IsMyHomeFolder = ismyhomefolder;
	}
	public Boolean getIsAStartFolder() {
		return IsAStartFolder;
	}

	public void setIsAStartFolder(Boolean isastartfolder) {
		IsAStartFolder = isastartfolder;
	}
	public Boolean getIsSharedFolder() {
		return IsSharedFolder;
	}

	public void setIsSharedFolder(Boolean issharedfolder) {
		IsSharedFolder = issharedfolder;
	}
	public Boolean getIsPassthrough() {
		return IsPassthrough;
	}

	public void setIsPassthrough(Boolean ispassthrough) {
		IsPassthrough = ispassthrough;
	}
	public Boolean getIsVersioned() {
		return IsVersioned;
	}

	public void setIsVersioned(Boolean isversioned) {
		IsVersioned = isversioned;
	}
	public Boolean getCanAddFolder() {
		return CanAddFolder;
	}

	public void setCanAddFolder(Boolean canaddfolder) {
		CanAddFolder = canaddfolder;
	}
	public Boolean getCanAddNode() {
		return CanAddNode;
	}

	public void setCanAddNode(Boolean canaddnode) {
		CanAddNode = canaddnode;
	}
	public Boolean getCanView() {
		return CanView;
	}

	public void setCanView(Boolean canview) {
		CanView = canview;
	}
	public Boolean getCanDownload() {
		return CanDownload;
	}

	public void setCanDownload(Boolean candownload) {
		CanDownload = candownload;
	}
	public Boolean getCanWatermarkDownload() {
		return CanWatermarkDownload;
	}

	public void setCanWatermarkDownload(Boolean canwatermarkdownload) {
		CanWatermarkDownload = canwatermarkdownload;
	}
	public Boolean getCanUpload() {
		return CanUpload;
	}

	public void setCanUpload(Boolean canupload) {
		CanUpload = canupload;
	}
	public Boolean getCanSend() {
		return CanSend;
	}

	public void setCanSend(Boolean cansend) {
		CanSend = cansend;
	}
	public Boolean getCanDeleteCurrentItem() {
		return CanDeleteCurrentItem;
	}

	public void setCanDeleteCurrentItem(Boolean candeletecurrentitem) {
		CanDeleteCurrentItem = candeletecurrentitem;
	}
	public Boolean getCanDeleteChildItems() {
		return CanDeleteChildItems;
	}

	public void setCanDeleteChildItems(Boolean candeletechilditems) {
		CanDeleteChildItems = candeletechilditems;
	}
	public Boolean getCanManagePermissions() {
		return CanManagePermissions;
	}

	public void setCanManagePermissions(Boolean canmanagepermissions) {
		CanManagePermissions = canmanagepermissions;
	}
	public Boolean getCanEditFolderOpts() {
		return CanEditFolderOpts;
	}

	public void setCanEditFolderOpts(Boolean caneditfolderopts) {
		CanEditFolderOpts = caneditfolderopts;
	}
	public String getFolderPayID() {
		return FolderPayID;
	}

	public void setFolderPayID(String folderpayid) {
		FolderPayID = folderpayid;
	}
	public Boolean getShowFolderPayBuyButton() {
		return ShowFolderPayBuyButton;
	}

	public void setShowFolderPayBuyButton(Boolean showfolderpaybuybutton) {
		ShowFolderPayBuyButton = showfolderpaybuybutton;
	}
	public SFTreeMode getTreeMode() {
		return TreeMode;
	}

	public void setTreeMode(SFTreeMode treemode) {
		TreeMode = treemode;
	}
	public Boolean getTreeModeOperationAllowed() {
		return TreeModeOperationAllowed;
	}

	public void setTreeModeOperationAllowed(Boolean treemodeoperationallowed) {
		TreeModeOperationAllowed = treemodeoperationallowed;
	}
	public String getTreeModeSourceId() {
		return TreeModeSourceId;
	}

	public void setTreeModeSourceId(String treemodesourceid) {
		TreeModeSourceId = treemodesourceid;
	}
}