
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

public class SFUserPreferences extends SFODataObject {

	private Boolean mEnableFlashUpload;
	private Boolean mEnableJavaUpload;
	private Boolean mEnableJavaDownload;
	private Boolean mRememberCustomMessages;
	private Boolean mRequireLoginByDefault;
	private Boolean mNotifyOnUploadByDefault;
	private Boolean mNotifyOnDownloadByDefault;
	private Boolean mCanResetPassword;
	private Boolean mCanViewMySettings;
	private Boolean mIsSharedUserAccount;
	private String mTimeZone;
	private String mDaylightSavingMode;
	private Integer mTimeZoneOffset;
	private Integer mTimeZoneOffsetMins;
	private Boolean mDisplayUserMessage;
	private String mUserMessageCode;
	private Integer mNotificationInterval;
	private Integer mShowTutorial;
	private Integer mEnableToolOverride;
	private Boolean mIsResetSecurityQuestionRequired;
	private String mTimeFormat;
	private String mLongTimeFormat;
	private String mDateFormat;

	public Boolean getEnableFlashUpload() {
		return mEnableFlashUpload;
	}

	public void setEnableFlashUpload(Boolean enableflashupload) {
		mEnableFlashUpload = enableflashupload;
	}
	public Boolean getEnableJavaUpload() {
		return mEnableJavaUpload;
	}

	public void setEnableJavaUpload(Boolean enablejavaupload) {
		mEnableJavaUpload = enablejavaupload;
	}
	public Boolean getEnableJavaDownload() {
		return mEnableJavaDownload;
	}

	public void setEnableJavaDownload(Boolean enablejavadownload) {
		mEnableJavaDownload = enablejavadownload;
	}
	public Boolean getRememberCustomMessages() {
		return mRememberCustomMessages;
	}

	public void setRememberCustomMessages(Boolean remembercustommessages) {
		mRememberCustomMessages = remembercustommessages;
	}
	public Boolean getRequireLoginByDefault() {
		return mRequireLoginByDefault;
	}

	public void setRequireLoginByDefault(Boolean requireloginbydefault) {
		mRequireLoginByDefault = requireloginbydefault;
	}
	public Boolean getNotifyOnUploadByDefault() {
		return mNotifyOnUploadByDefault;
	}

	public void setNotifyOnUploadByDefault(Boolean notifyonuploadbydefault) {
		mNotifyOnUploadByDefault = notifyonuploadbydefault;
	}
	public Boolean getNotifyOnDownloadByDefault() {
		return mNotifyOnDownloadByDefault;
	}

	public void setNotifyOnDownloadByDefault(Boolean notifyondownloadbydefault) {
		mNotifyOnDownloadByDefault = notifyondownloadbydefault;
	}
	public Boolean getCanResetPassword() {
		return mCanResetPassword;
	}

	public void setCanResetPassword(Boolean canresetpassword) {
		mCanResetPassword = canresetpassword;
	}
	public Boolean getCanViewMySettings() {
		return mCanViewMySettings;
	}

	public void setCanViewMySettings(Boolean canviewmysettings) {
		mCanViewMySettings = canviewmysettings;
	}
	public Boolean getIsSharedUserAccount() {
		return mIsSharedUserAccount;
	}

	public void setIsSharedUserAccount(Boolean isshareduseraccount) {
		mIsSharedUserAccount = isshareduseraccount;
	}
	public String getTimeZone() {
		return mTimeZone;
	}

	public void setTimeZone(String timezone) {
		mTimeZone = timezone;
	}
	public String getDaylightSavingMode() {
		return mDaylightSavingMode;
	}

	public void setDaylightSavingMode(String daylightsavingmode) {
		mDaylightSavingMode = daylightsavingmode;
	}
	public Integer getTimeZoneOffset() {
		return mTimeZoneOffset;
	}

	public void setTimeZoneOffset(Integer timezoneoffset) {
		mTimeZoneOffset = timezoneoffset;
	}
	public Integer getTimeZoneOffsetMins() {
		return mTimeZoneOffsetMins;
	}

	public void setTimeZoneOffsetMins(Integer timezoneoffsetmins) {
		mTimeZoneOffsetMins = timezoneoffsetmins;
	}
	public Boolean getDisplayUserMessage() {
		return mDisplayUserMessage;
	}

	public void setDisplayUserMessage(Boolean displayusermessage) {
		mDisplayUserMessage = displayusermessage;
	}
	public String getUserMessageCode() {
		return mUserMessageCode;
	}

	public void setUserMessageCode(String usermessagecode) {
		mUserMessageCode = usermessagecode;
	}
	public Integer getNotificationInterval() {
		return mNotificationInterval;
	}

	public void setNotificationInterval(Integer notificationinterval) {
		mNotificationInterval = notificationinterval;
	}
	public Integer getShowTutorial() {
		return mShowTutorial;
	}

	public void setShowTutorial(Integer showtutorial) {
		mShowTutorial = showtutorial;
	}
	public Integer getEnableToolOverride() {
		return mEnableToolOverride;
	}

	public void setEnableToolOverride(Integer enabletooloverride) {
		mEnableToolOverride = enabletooloverride;
	}
	public Boolean getIsResetSecurityQuestionRequired() {
		return mIsResetSecurityQuestionRequired;
	}

	public void setIsResetSecurityQuestionRequired(Boolean isresetsecurityquestionrequired) {
		mIsResetSecurityQuestionRequired = isresetsecurityquestionrequired;
	}
	public String getTimeFormat() {
		return mTimeFormat;
	}

	public void setTimeFormat(String timeformat) {
		mTimeFormat = timeformat;
	}
	public String getLongTimeFormat() {
		return mLongTimeFormat;
	}

	public void setLongTimeFormat(String longtimeformat) {
		mLongTimeFormat = longtimeformat;
	}
	public String getDateFormat() {
		return mDateFormat;
	}

	public void setDateFormat(String dateformat) {
		mDateFormat = dateformat;
	}
}