// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2015 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.entities.internal;

import com.sharefile.api.entities.ISFEntities;

public interface ISFInternalEntities extends ISFEntities {
    public static abstract class Implementation extends ISFEntities.Implementation implements ISFInternalEntities
    {
        @Override
        public com.sharefile.api.entities.internal.SFBillingEntityInternal billing() {
            return (com.sharefile.api.entities.internal.SFBillingEntityInternal) getEntity(com.sharefile.api.entities.internal.SFBillingEntityInternal.class);
        }
        

        @Override
        public com.sharefile.api.entities.internal.SFEncryptedEmailsEntityInternal encryptedEmails() {
            return (com.sharefile.api.entities.internal.SFEncryptedEmailsEntityInternal) getEntity(com.sharefile.api.entities.internal.SFEncryptedEmailsEntityInternal.class);
        }
        

        @Override
        public com.sharefile.api.entities.internal.SFFileLockEntityInternal fileLock() {
            return (com.sharefile.api.entities.internal.SFFileLockEntityInternal) getEntity(com.sharefile.api.entities.internal.SFFileLockEntityInternal.class);
        }
        

        @Override
        public com.sharefile.api.entities.internal.SFNotificationsEntityInternal notifications() {
            return (com.sharefile.api.entities.internal.SFNotificationsEntityInternal) getEntity(com.sharefile.api.entities.internal.SFNotificationsEntityInternal.class);
        }
        

        @Override
        public com.sharefile.api.entities.internal.SFOAuthClientsEntityInternal oAuthClients() {
            return (com.sharefile.api.entities.internal.SFOAuthClientsEntityInternal) getEntity(com.sharefile.api.entities.internal.SFOAuthClientsEntityInternal.class);
        }
        

        @Override
        public com.sharefile.api.entities.internal.SFPlanAddonsEntityInternal planAddons() {
            return (com.sharefile.api.entities.internal.SFPlanAddonsEntityInternal) getEntity(com.sharefile.api.entities.internal.SFPlanAddonsEntityInternal.class);
        }
        

        @Override
        public com.sharefile.api.entities.internal.SFReportsEntityInternal reports() {
            return (com.sharefile.api.entities.internal.SFReportsEntityInternal) getEntity(com.sharefile.api.entities.internal.SFReportsEntityInternal.class);
        }
        

        @Override
        public com.sharefile.api.entities.internal.SFUsagePlansEntityInternal usagePlans() {
            return (com.sharefile.api.entities.internal.SFUsagePlansEntityInternal) getEntity(com.sharefile.api.entities.internal.SFUsagePlansEntityInternal.class);
        }
        

        @Override
        public com.sharefile.api.entities.internal.SFFolderTemplatesEntityInternal folderTemplatesInternal() {
            return (com.sharefile.api.entities.internal.SFFolderTemplatesEntityInternal) getEntity(com.sharefile.api.entities.internal.SFFolderTemplatesEntityInternal.class);
        }
        

        @Override
        public com.sharefile.api.entities.internal.SFAccountsEntityInternal accountsInternal() {
            return (com.sharefile.api.entities.internal.SFAccountsEntityInternal) getEntity(com.sharefile.api.entities.internal.SFAccountsEntityInternal.class);
        }
        

        @Override
        public com.sharefile.api.entities.internal.SFAzureSBTopicsEntityInternal azureSBTopics() {
            return (com.sharefile.api.entities.internal.SFAzureSBTopicsEntityInternal) getEntity(com.sharefile.api.entities.internal.SFAzureSBTopicsEntityInternal.class);
        }
        

        @Override
        public com.sharefile.api.entities.internal.SFConfigsEntityInternal configs() {
            return (com.sharefile.api.entities.internal.SFConfigsEntityInternal) getEntity(com.sharefile.api.entities.internal.SFConfigsEntityInternal.class);
        }
        

        @Override
        public com.sharefile.api.entities.internal.SFDevicesEntityInternal devices() {
            return (com.sharefile.api.entities.internal.SFDevicesEntityInternal) getEntity(com.sharefile.api.entities.internal.SFDevicesEntityInternal.class);
        }
        

        @Override
        public com.sharefile.api.entities.internal.SFItemsEntityInternal itemsInternal() {
            return (com.sharefile.api.entities.internal.SFItemsEntityInternal) getEntity(com.sharefile.api.entities.internal.SFItemsEntityInternal.class);
        }
        

        @Override
        public com.sharefile.api.entities.internal.SFUsersEntityInternal usersInternal() {
            return (com.sharefile.api.entities.internal.SFUsersEntityInternal) getEntity(com.sharefile.api.entities.internal.SFUsersEntityInternal.class);
        }
        

    }

    com.sharefile.api.entities.internal.SFBillingEntityInternal billing();
    SFEncryptedEmailsEntityInternal encryptedEmails();
    SFFileLockEntityInternal fileLock();
    SFNotificationsEntityInternal notifications();
    SFOAuthClientsEntityInternal oAuthClients();
    SFPlanAddonsEntityInternal planAddons();
    SFReportsEntityInternal reports();
    SFUsagePlansEntityInternal usagePlans();
    SFFolderTemplatesEntityInternal folderTemplatesInternal();
    SFAccountsEntityInternal accountsInternal();
    SFAzureSBTopicsEntityInternal azureSBTopics();
    SFConfigsEntityInternal configs();
    SFDevicesEntityInternal devices();
    SFItemsEntityInternal itemsInternal();
    SFUsersEntityInternal usersInternal();
}