
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2015 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.entities.internal;

import com.citrix.sharefile.api.entities.*;
import com.citrix.sharefile.api.interfaces.ISFApiClient;
import com.citrix.sharefile.api.models.*;
import com.citrix.sharefile.api.models.internal.*;
import com.citrix.sharefile.api.SFApiQuery;
import com.citrix.sharefile.api.interfaces.ISFQuery;


import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
 
import com.google.gson.annotations.SerializedName;
import com.citrix.sharefile.api.enumerations.SFSafeEnum;
import com.citrix.sharefile.api.enumerations.SFSafeEnumFlags;

public class SFFolderTemplatesEntityInternal extends SFFolderTemplatesEntity
{
    public SFFolderTemplatesEntityInternal(ISFApiClient client) {
        super(client);
    }

    public ISFQuery<SFAsyncOperation> bulkApply(URI url, String folderId, Integer batchSize)
	{
		SFApiQuery<SFAsyncOperation> sfApiQuery = new SFApiQuery<SFAsyncOperation>(this.apiClient);
		sfApiQuery.setFrom("FolderTemplates");
		sfApiQuery.setAction("BulkApply");
		sfApiQuery.addIds(url);
		sfApiQuery.addQueryString("folderId", folderId);
		sfApiQuery.addQueryString("batchSize", batchSize);
		sfApiQuery.setHttpMethod("POST");
		return sfApiQuery;
	}

}

