
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models.Private;

import com.sharefile.api.models.SFODataObject;

public class SFOutlookInformation extends SFODataObject {

	private SFOutlookInformationOptionString DownloadInfoLevel;
	private SFOutlookInformationOptionString UploadInfoLevel;
	private SFOutlookInformationOptionBool NotifyOnDownload;
	private SFOutlookInformationOptionBool NotifyOnUpload;
	private SFOutlookInformationOptionInt MaxDownloads;
	private SFOutlookInformationOptionString LinkExpiration;
	private SFOutlookInformationOptionString RequestText;
	private SFOutlookInformationOptionString SendText;
	private SFOutlookInformationOptionString BannerHTML;
	private SFOutlookInformationOptionBool UseBanner;
	private SFOutlookInformationOptionBool AutoConvert;
	private SFOutlookInformationOptionInt ConvertAbove;
	private SFOutlookInformationOptionBool AttachPaperclip;

	public SFOutlookInformationOptionString getDownloadInfoLevel() {
		return DownloadInfoLevel;
	}

	public void setDownloadInfoLevel(SFOutlookInformationOptionString downloadinfolevel) {
		DownloadInfoLevel = downloadinfolevel;
	}
	public SFOutlookInformationOptionString getUploadInfoLevel() {
		return UploadInfoLevel;
	}

	public void setUploadInfoLevel(SFOutlookInformationOptionString uploadinfolevel) {
		UploadInfoLevel = uploadinfolevel;
	}
	public SFOutlookInformationOptionBool getNotifyOnDownload() {
		return NotifyOnDownload;
	}

	public void setNotifyOnDownload(SFOutlookInformationOptionBool notifyondownload) {
		NotifyOnDownload = notifyondownload;
	}
	public SFOutlookInformationOptionBool getNotifyOnUpload() {
		return NotifyOnUpload;
	}

	public void setNotifyOnUpload(SFOutlookInformationOptionBool notifyonupload) {
		NotifyOnUpload = notifyonupload;
	}
	public SFOutlookInformationOptionInt getMaxDownloads() {
		return MaxDownloads;
	}

	public void setMaxDownloads(SFOutlookInformationOptionInt maxdownloads) {
		MaxDownloads = maxdownloads;
	}
	public SFOutlookInformationOptionString getLinkExpiration() {
		return LinkExpiration;
	}

	public void setLinkExpiration(SFOutlookInformationOptionString linkexpiration) {
		LinkExpiration = linkexpiration;
	}
	public SFOutlookInformationOptionString getRequestText() {
		return RequestText;
	}

	public void setRequestText(SFOutlookInformationOptionString requesttext) {
		RequestText = requesttext;
	}
	public SFOutlookInformationOptionString getSendText() {
		return SendText;
	}

	public void setSendText(SFOutlookInformationOptionString sendtext) {
		SendText = sendtext;
	}
	public SFOutlookInformationOptionString getBannerHTML() {
		return BannerHTML;
	}

	public void setBannerHTML(SFOutlookInformationOptionString bannerhtml) {
		BannerHTML = bannerhtml;
	}
	public SFOutlookInformationOptionBool getUseBanner() {
		return UseBanner;
	}

	public void setUseBanner(SFOutlookInformationOptionBool usebanner) {
		UseBanner = usebanner;
	}
	public SFOutlookInformationOptionBool getAutoConvert() {
		return AutoConvert;
	}

	public void setAutoConvert(SFOutlookInformationOptionBool autoconvert) {
		AutoConvert = autoconvert;
	}
	public SFOutlookInformationOptionInt getConvertAbove() {
		return ConvertAbove;
	}

	public void setConvertAbove(SFOutlookInformationOptionInt convertabove) {
		ConvertAbove = convertabove;
	}
	public SFOutlookInformationOptionBool getAttachPaperclip() {
		return AttachPaperclip;
	}

	public void setAttachPaperclip(SFOutlookInformationOptionBool attachpaperclip) {
		AttachPaperclip = attachpaperclip;
	}
}