// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2015 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------
package com.sharefile.api.internal.models

import com.sharefile.api.models.*;

public class EntityTypeMapInternal
{
    private static bool registered = false;
    private static Object mapLock = new Object();

    public static void registerInternalModels() {
        synchronized (mapLock) {
            if(registered) {
                return;
            }

            EntityTypeMap.addEntity("AppliedPlanAddOns", SFAppliedPlanAddOns.class);
            EntityTypeMap.addEntity("AppliedPlanAddOnss", SFAppliedPlanAddOns.class);
            EntityTypeMap.addEntity("Billing", SFBilling.class);
            EntityTypeMap.addEntity("Billings", SFBilling.class);
            EntityTypeMap.addEntity("ReportRecord", SFReportRecord.class);
            EntityTypeMap.addEntity("ReportRecords", SFReportRecord.class);
            EntityTypeMap.addEntity("BillingAddOn", SFBillingAddOn.class);
            EntityTypeMap.addEntity("BillingAddOns", SFBillingAddOn.class);
            EntityTypeMap.addEntity("CustomBillingEntry", SFCustomBillingEntry.class);
            EntityTypeMap.addEntity("CustomBillingEntrys", SFCustomBillingEntry.class);
            EntityTypeMap.addEntity("EncryptedEmailParams", SFEncryptedEmailParams.class);
            EntityTypeMap.addEntity("EncryptedEmailParamss", SFEncryptedEmailParams.class);
            EntityTypeMap.addEntity("EncryptedEmailReplyParams", SFEncryptedEmailReplyParams.class);
            EntityTypeMap.addEntity("EncryptedEmailReplyParamss", SFEncryptedEmailReplyParams.class);
            EntityTypeMap.addEntity("EncryptedEmailCreateParams", SFEncryptedEmailCreateParams.class);
            EntityTypeMap.addEntity("EncryptedEmailCreateParamss", SFEncryptedEmailCreateParams.class);
            EntityTypeMap.addEntity("EnterpriseOrder", SFEnterpriseOrder.class);
            EntityTypeMap.addEntity("EnterpriseOrders", SFEnterpriseOrder.class);
            EntityTypeMap.addEntity("EnterpriseReseller", SFEnterpriseReseller.class);
            EntityTypeMap.addEntity("EnterpriseResellers", SFEnterpriseReseller.class);
            EntityTypeMap.addEntity("EncryptedEmail", SFEncryptedEmail.class);
            EntityTypeMap.addEntity("EncryptedEmails", SFEncryptedEmail.class);
            EntityTypeMap.addEntity("EncryptedEmailSendParams", SFEncryptedEmailSendParams.class);
            EntityTypeMap.addEntity("EncryptedEmailSendParamss", SFEncryptedEmailSendParams.class);
            EntityTypeMap.addEntity("EncryptedEmailRecipient", SFEncryptedEmailRecipient.class);
            EntityTypeMap.addEntity("EncryptedEmailRecipients", SFEncryptedEmailRecipient.class);
            EntityTypeMap.addEntity("OAuthCode", SFOAuthCode.class);
            EntityTypeMap.addEntity("OAuthCodes", SFOAuthCode.class);
            EntityTypeMap.addEntity("PlanAddon", SFPlanAddon.class);
            EntityTypeMap.addEntity("PlanAddons", SFPlanAddon.class);
            EntityTypeMap.addEntity("InAppPurchase", SFInAppPurchase.class);
            EntityTypeMap.addEntity("InAppPurchases", SFInAppPurchase.class);
            EntityTypeMap.addEntity("TrialPeriod", SFTrialPeriod.class);
            EntityTypeMap.addEntity("TrialPeriods", SFTrialPeriod.class);
            EntityTypeMap.addEntity("PlanAddonUser", SFPlanAddonUser.class);
            EntityTypeMap.addEntity("PlanAddonUsers", SFPlanAddonUser.class);
            EntityTypeMap.addEntity("OAuthClient", SFOAuthClient.class);
            EntityTypeMap.addEntity("OAuthClients", SFOAuthClient.class);
            EntityTypeMap.addEntity("Report", SFReport.class);
            EntityTypeMap.addEntity("Reports", SFReport.class);
            EntityTypeMap.addEntity("Reseller", SFReseller.class);
            EntityTypeMap.addEntity("Resellers", SFReseller.class);
            EntityTypeMap.addEntity("ShareFileRepresentative", SFShareFileRepresentative.class);
            EntityTypeMap.addEntity("ShareFileRepresentatives", SFShareFileRepresentative.class);
            EntityTypeMap.addEntity("FreeTrialAccount", SFFreeTrialAccount.class);
            EntityTypeMap.addEntity("FreeTrialAccounts", SFFreeTrialAccount.class);
            EntityTypeMap.addEntity("Queue", SFQueue.class);
            EntityTypeMap.addEntity("Queues", SFQueue.class);
            EntityTypeMap.addEntity("QueueEntry", SFQueueEntry.class);
            EntityTypeMap.addEntity("QueueEntries", SFQueueEntry.class);
            EntityTypeMap.addEntity("AzureSBTopicsEndPointInfo", SFAzureSBTopicsEndPointInfo.class);
            EntityTypeMap.addEntity("AzureSBTopicsEndPointInfos", SFAzureSBTopicsEndPointInfo.class);
            EntityTypeMap.addEntity("AzureSBTopicsResponse", SFAzureSBTopicsResponse.class);
            EntityTypeMap.addEntity("AzureSBTopicsResponses", SFAzureSBTopicsResponse.class);
            EntityTypeMap.addEntity("UsagePlan", SFUsagePlan.class);
            EntityTypeMap.addEntity("UsagePlans", SFUsagePlan.class);
            EntityTypeMap.addEntity("UsagePlanAddOn", SFUsagePlanAddOn.class);
            EntityTypeMap.addEntity("UsagePlanAddOns", SFUsagePlanAddOn.class);

            registered = true;
        }
    }
}