






// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------


package com.sharefile.api.models;


public class SFAccount extends SFODataObject {



	@SerializedName("CompanyName")

	private String CompanyName;


	@SerializedName("BillingContact")

	private SFUser BillingContact;


	@SerializedName("BillingContactId")

	private String BillingContactId;


	@SerializedName("TechnicalContact")

	private SFUser TechnicalContact;


	@SerializedName("TechnicalContactId")

	private String TechnicalContactId;


	@SerializedName("AccountManager")

	private SFUser AccountManager;


	@SerializedName("AccountManagerId")

	private String AccountManagerId;


	@SerializedName("AccountType")

	private String AccountType;


	@SerializedName("PlanName")

	private String PlanName;


	@SerializedName("PlanTrack")

	private String PlanTrack;


	@SerializedName("PlanTrackEnum")

	private String PlanTrackEnum;


	@SerializedName("BillingType")

	private String BillingType;


	@SerializedName("BillingCycle")

	private String BillingCycle;


	@SerializedName("BillingRate")

	private Double BillingRate;


	@SerializedName("BaseBillingRate")

	private Double BaseBillingRate;


	@SerializedName("BaseBandwidth")

	private Integer BaseBandwidth;


	@SerializedName("BaseDiskSpace")

	private Integer BaseDiskSpace;


	@SerializedName("BaseUsers")

	private Integer BaseUsers;


	@SerializedName("AdditionalBandwidth")

	private Integer AdditionalBandwidth;


	@SerializedName("AdditionalDiskSpace")

	private Integer AdditionalDiskSpace;


	@SerializedName("AdditionalUsers")

	private Integer AdditionalUsers;


	@SerializedName("AdditionalBandwidthRate")

	private Double AdditionalBandwidthRate;


	@SerializedName("AdditionalDiskSpaceRate")

	private Double AdditionalDiskSpaceRate;


	@SerializedName("AdditionalUserRate")

	private Double AdditionalUserRate;


	@SerializedName("UserMax")

	private Integer UserMax;


	@SerializedName("DiskSpaceMax")

	private Integer DiskSpaceMax;


	@SerializedName("BandwidthMax")

	private Integer BandwidthMax;


	@SerializedName("HasPowerTools")

	private Boolean HasPowerTools;


	@SerializedName("HasEncryption")

	private Boolean HasEncryption;


	@SerializedName("PowerToolsRate")

	private Double PowerToolsRate;


	@SerializedName("EncryptionRate")

	private Double EncryptionRate;


	@SerializedName("Address1")

	private String Address1;


	@SerializedName("Address2")

	private String Address2;


	@SerializedName("City")

	private String City;


	@SerializedName("State")

	private String State;


	@SerializedName("Zip")

	private String Zip;


	@SerializedName("Country")

	private String Country;


	@SerializedName("CreditCardType")

	private String CreditCardType;


	@SerializedName("CreditCardNumber")

	private String CreditCardNumber;


	@SerializedName("CreditCardExpirationMonth")

	private String CreditCardExpirationMonth;


	@SerializedName("CreditCardExpirationYear")

	private String CreditCardExpirationYear;


	@SerializedName("CreditCardFirstName")

	private String CreditCardFirstName;


	@SerializedName("CreditCardLastName")

	private String CreditCardLastName;


	@SerializedName("Phone")

	private String Phone;


	@SerializedName("LastBillingDate")

	private Date LastBillingDate;


	@SerializedName("NextBillingDate")

	private Date NextBillingDate;


	@SerializedName("UseAdvancedCustomBranding")

	private Boolean UseAdvancedCustomBranding;


	@SerializedName("AdvancedCustomBrandingFolderName")

	private String AdvancedCustomBrandingFolderName;


	@SerializedName("BrandingStyles")

	private Map<String, String> BrandingStyles;


	@SerializedName("LogoURL")

	private String LogoURL;


	@SerializedName("RootItem")

	private SFItem RootItem;


	@SerializedName("RootItemId")

	private String RootItemId;


	@SerializedName("CreationDate")

	private Date CreationDate;


	@SerializedName("IsFreeTrial")

	private Boolean IsFreeTrial;


	@SerializedName("IsCancelled")

	private Boolean IsCancelled;


	@SerializedName("CancellationDate")

	private Date CancellationDate;


	@SerializedName("SSO")

	private SFSSOAccountProvider SSO;


	@SerializedName("Preferences")

	private SFAccountPreferences Preferences;


	@SerializedName("ProductDefaults")

	private SFProductDefaults ProductDefaults;


	@SerializedName("Subdomain")

	private String Subdomain;


	@SerializedName("Subdomains")

	private ArrayList<String> Subdomains;


	@SerializedName("MobileSecuritySettings")

	private SFMobileSecuritySettings MobileSecuritySettings;


	@SerializedName("LoginAccessControlDomains")

	private SFAccessControlDomains LoginAccessControlDomains;


	@SerializedName("FolderAccessControlDomains")

	private SFAccessControlDomains FolderAccessControlDomains;


	@SerializedName("StorageQuotaPerUser")

	private Integer StorageQuotaPerUser;


	@SerializedName("FreeTrialId")

	private String FreeTrialId;


	@SerializedName("Source")

	private String Source;


	@SerializedName("AttributedSource")

	private String AttributedSource;


	@SerializedName("CompanyURL")

	private String CompanyURL;


	@SerializedName("MarketingOptIn")

	private Boolean MarketingOptIn;


	@SerializedName("CreditCardSecurityCode")

	private String CreditCardSecurityCode;


	@SerializedName("ToolInformation")

	private ArrayList<SFToolInformation> ToolInformation;




	public String getCompanyName() {
		return CompanyName;
	}


	public void setCompanyName(String companyname) {
		CompanyName = companyname;
	}


	public SFUser getBillingContact() {
		return BillingContact;
	}


	public void setBillingContact(SFUser billingcontact) {
		BillingContact = billingcontact;
	}


	public String getBillingContactId() {
		return BillingContactId;
	}


	public void setBillingContactId(String billingcontactid) {
		BillingContactId = billingcontactid;
	}


	public SFUser getTechnicalContact() {
		return TechnicalContact;
	}


	public void setTechnicalContact(SFUser technicalcontact) {
		TechnicalContact = technicalcontact;
	}


	public String getTechnicalContactId() {
		return TechnicalContactId;
	}


	public void setTechnicalContactId(String technicalcontactid) {
		TechnicalContactId = technicalcontactid;
	}


	public SFUser getAccountManager() {
		return AccountManager;
	}


	public void setAccountManager(SFUser accountmanager) {
		AccountManager = accountmanager;
	}


	public String getAccountManagerId() {
		return AccountManagerId;
	}


	public void setAccountManagerId(String accountmanagerid) {
		AccountManagerId = accountmanagerid;
	}


	public String getAccountType() {
		return AccountType;
	}


	public void setAccountType(String accounttype) {
		AccountType = accounttype;
	}


		/**

		* Basic, Professional, Enterprise

		*/

	public String getPlanName() {
		return PlanName;
	}


		/**

		* Basic, Professional, Enterprise

		*/

	public void setPlanName(String planname) {
		PlanName = planname;
	}


	public String getPlanTrack() {
		return PlanTrack;
	}


	public void setPlanTrack(String plantrack) {
		PlanTrack = plantrack;
	}


	public String getPlanTrackEnum() {
		return PlanTrackEnum;
	}


	public void setPlanTrackEnum(String plantrackenum) {
		PlanTrackEnum = plantrackenum;
	}


		/**

		* Credit Card, Invoice, Comp

		*/

	public String getBillingType() {
		return BillingType;
	}


		/**

		* Credit Card, Invoice, Comp

		*/

	public void setBillingType(String billingtype) {
		BillingType = billingtype;
	}


		/**

		* Monthly, Quarterly, Annually

		*/

	public String getBillingCycle() {
		return BillingCycle;
	}


		/**

		* Monthly, Quarterly, Annually

		*/

	public void setBillingCycle(String billingcycle) {
		BillingCycle = billingcycle;
	}


	public Double getBillingRate() {
		return BillingRate;
	}


	public void setBillingRate(Double billingrate) {
		BillingRate = billingrate;
	}


	public Double getBaseBillingRate() {
		return BaseBillingRate;
	}


	public void setBaseBillingRate(Double basebillingrate) {
		BaseBillingRate = basebillingrate;
	}


		/**

		* Bandwidth included in plan in megabytes

		*/

	public Integer getBaseBandwidth() {
		return BaseBandwidth;
	}


		/**

		* Bandwidth included in plan in megabytes

		*/

	public void setBaseBandwidth(Integer basebandwidth) {
		BaseBandwidth = basebandwidth;
	}


		/**

		* Disk space included in megabytes

		*/

	public Integer getBaseDiskSpace() {
		return BaseDiskSpace;
	}


		/**

		* Disk space included in megabytes

		*/

	public void setBaseDiskSpace(Integer basediskspace) {
		BaseDiskSpace = basediskspace;
	}


		/**

		* Users included in plan

		*/

	public Integer getBaseUsers() {
		return BaseUsers;
	}


		/**

		* Users included in plan

		*/

	public void setBaseUsers(Integer baseusers) {
		BaseUsers = baseusers;
	}


		/**

		* Additional bandwidth purchased for account

		*/

	public Integer getAdditionalBandwidth() {
		return AdditionalBandwidth;
	}


		/**

		* Additional bandwidth purchased for account

		*/

	public void setAdditionalBandwidth(Integer additionalbandwidth) {
		AdditionalBandwidth = additionalbandwidth;
	}


		/**

		* Additional disk space purchased for account

		*/

	public Integer getAdditionalDiskSpace() {
		return AdditionalDiskSpace;
	}


		/**

		* Additional disk space purchased for account

		*/

	public void setAdditionalDiskSpace(Integer additionaldiskspace) {
		AdditionalDiskSpace = additionaldiskspace;
	}


		/**

		* Additional users purchased for account

		*/

	public Integer getAdditionalUsers() {
		return AdditionalUsers;
	}


		/**

		* Additional users purchased for account

		*/

	public void setAdditionalUsers(Integer additionalusers) {
		AdditionalUsers = additionalusers;
	}


		/**

		* Additional rate for extra bandwidth. NOTE: This is specified in gigbytes, not megabytes.

		*/

	public Double getAdditionalBandwidthRate() {
		return AdditionalBandwidthRate;
	}


		/**

		* Additional rate for extra bandwidth. NOTE: This is specified in gigbytes, not megabytes.

		*/

	public void setAdditionalBandwidthRate(Double additionalbandwidthrate) {
		AdditionalBandwidthRate = additionalbandwidthrate;
	}


		/**

		* Additional rate for extra diskspace. NOTE: This is specified in gigbytes, not megabytes.

		*/

	public Double getAdditionalDiskSpaceRate() {
		return AdditionalDiskSpaceRate;
	}


		/**

		* Additional rate for extra diskspace. NOTE: This is specified in gigbytes, not megabytes.

		*/

	public void setAdditionalDiskSpaceRate(Double additionaldiskspacerate) {
		AdditionalDiskSpaceRate = additionaldiskspacerate;
	}


		/**

		* Additional rate for extra users

		*/

	public Double getAdditionalUserRate() {
		return AdditionalUserRate;
	}


		/**

		* Additional rate for extra users

		*/

	public void setAdditionalUserRate(Double additionaluserrate) {
		AdditionalUserRate = additionaluserrate;
	}


	public Integer getUserMax() {
		return UserMax;
	}


	public void setUserMax(Integer usermax) {
		UserMax = usermax;
	}


		/**

		* Maximum disk space for the account in megabtyes

		*/

	public Integer getDiskSpaceMax() {
		return DiskSpaceMax;
	}


		/**

		* Maximum disk space for the account in megabtyes

		*/

	public void setDiskSpaceMax(Integer diskspacemax) {
		DiskSpaceMax = diskspacemax;
	}


		/**

		* Maximum bandwidth for the account in megabtyes

		*/

	public Integer getBandwidthMax() {
		return BandwidthMax;
	}


		/**

		* Maximum bandwidth for the account in megabtyes

		*/

	public void setBandwidthMax(Integer bandwidthmax) {
		BandwidthMax = bandwidthmax;
	}


	public Boolean getHasPowerTools() {
		return HasPowerTools;
	}


	public void setHasPowerTools(Boolean haspowertools) {
		HasPowerTools = haspowertools;
	}


	public Boolean getHasEncryption() {
		return HasEncryption;
	}


	public void setHasEncryption(Boolean hasencryption) {
		HasEncryption = hasencryption;
	}


		/**

		* Additional rate for adding PowerTools.

		*/

	public Double getPowerToolsRate() {
		return PowerToolsRate;
	}


		/**

		* Additional rate for adding PowerTools.

		*/

	public void setPowerToolsRate(Double powertoolsrate) {
		PowerToolsRate = powertoolsrate;
	}


		/**

		* Additional rate for stored file encryption

		*/

	public Double getEncryptionRate() {
		return EncryptionRate;
	}


		/**

		* Additional rate for stored file encryption

		*/

	public void setEncryptionRate(Double encryptionrate) {
		EncryptionRate = encryptionrate;
	}


	public String getAddress1() {
		return Address1;
	}


	public void setAddress1(String address1) {
		Address1 = address1;
	}


	public String getAddress2() {
		return Address2;
	}


	public void setAddress2(String address2) {
		Address2 = address2;
	}


	public String getCity() {
		return City;
	}


	public void setCity(String city) {
		City = city;
	}


	public String getState() {
		return State;
	}


	public void setState(String state) {
		State = state;
	}


	public String getZip() {
		return Zip;
	}


	public void setZip(String zip) {
		Zip = zip;
	}


	public String getCountry() {
		return Country;
	}


	public void setCountry(String country) {
		Country = country;
	}


	public String getCreditCardType() {
		return CreditCardType;
	}


	public void setCreditCardType(String creditcardtype) {
		CreditCardType = creditcardtype;
	}


	public String getCreditCardNumber() {
		return CreditCardNumber;
	}


	public void setCreditCardNumber(String creditcardnumber) {
		CreditCardNumber = creditcardnumber;
	}


	public String getCreditCardExpirationMonth() {
		return CreditCardExpirationMonth;
	}


	public void setCreditCardExpirationMonth(String creditcardexpirationmonth) {
		CreditCardExpirationMonth = creditcardexpirationmonth;
	}


	public String getCreditCardExpirationYear() {
		return CreditCardExpirationYear;
	}


	public void setCreditCardExpirationYear(String creditcardexpirationyear) {
		CreditCardExpirationYear = creditcardexpirationyear;
	}


	public String getCreditCardFirstName() {
		return CreditCardFirstName;
	}


	public void setCreditCardFirstName(String creditcardfirstname) {
		CreditCardFirstName = creditcardfirstname;
	}


	public String getCreditCardLastName() {
		return CreditCardLastName;
	}


	public void setCreditCardLastName(String creditcardlastname) {
		CreditCardLastName = creditcardlastname;
	}


	public String getPhone() {
		return Phone;
	}


	public void setPhone(String phone) {
		Phone = phone;
	}


	public Date getLastBillingDate() {
		return LastBillingDate;
	}


	public void setLastBillingDate(Date lastbillingdate) {
		LastBillingDate = lastbillingdate;
	}


	public Date getNextBillingDate() {
		return NextBillingDate;
	}


	public void setNextBillingDate(Date nextbillingdate) {
		NextBillingDate = nextbillingdate;
	}


	public Boolean getUseAdvancedCustomBranding() {
		return UseAdvancedCustomBranding;
	}


	public void setUseAdvancedCustomBranding(Boolean useadvancedcustombranding) {
		UseAdvancedCustomBranding = useadvancedcustombranding;
	}


	public String getAdvancedCustomBrandingFolderName() {
		return AdvancedCustomBrandingFolderName;
	}


	public void setAdvancedCustomBrandingFolderName(String advancedcustombrandingfoldername) {
		AdvancedCustomBrandingFolderName = advancedcustombrandingfoldername;
	}


	public Map<String, String> getBrandingStyles() {
		return BrandingStyles;
	}


	public void setBrandingStyles(Map<String, String> brandingstyles) {
		BrandingStyles = brandingstyles;
	}


	public String getLogoURL() {
		return LogoURL;
	}


	public void setLogoURL(String logourl) {
		LogoURL = logourl;
	}


	public SFItem getRootItem() {
		return RootItem;
	}


	public void setRootItem(SFItem rootitem) {
		RootItem = rootitem;
	}


	public String getRootItemId() {
		return RootItemId;
	}


	public void setRootItemId(String rootitemid) {
		RootItemId = rootitemid;
	}


	public Date getCreationDate() {
		return CreationDate;
	}


	public void setCreationDate(Date creationdate) {
		CreationDate = creationdate;
	}


	public Boolean getIsFreeTrial() {
		return IsFreeTrial;
	}


	public void setIsFreeTrial(Boolean isfreetrial) {
		IsFreeTrial = isfreetrial;
	}


	public Boolean getIsCancelled() {
		return IsCancelled;
	}


	public void setIsCancelled(Boolean iscancelled) {
		IsCancelled = iscancelled;
	}


	public Date getCancellationDate() {
		return CancellationDate;
	}


	public void setCancellationDate(Date cancellationdate) {
		CancellationDate = cancellationdate;
	}


	public SFSSOAccountProvider getSSO() {
		return SSO;
	}


	public void setSSO(SFSSOAccountProvider sso) {
		SSO = sso;
	}


	public SFAccountPreferences getPreferences() {
		return Preferences;
	}


	public void setPreferences(SFAccountPreferences preferences) {
		Preferences = preferences;
	}


	public SFProductDefaults getProductDefaults() {
		return ProductDefaults;
	}


	public void setProductDefaults(SFProductDefaults productdefaults) {
		ProductDefaults = productdefaults;
	}


	public String getSubdomain() {
		return Subdomain;
	}


	public void setSubdomain(String subdomain) {
		Subdomain = subdomain;
	}


	public ArrayList<String> getSubdomains() {
		return Subdomains;
	}


	public void setSubdomains(ArrayList<String> subdomains) {
		Subdomains = subdomains;
	}


	public SFMobileSecuritySettings getMobileSecuritySettings() {
		return MobileSecuritySettings;
	}


	public void setMobileSecuritySettings(SFMobileSecuritySettings mobilesecuritysettings) {
		MobileSecuritySettings = mobilesecuritysettings;
	}


	public SFAccessControlDomains getLoginAccessControlDomains() {
		return LoginAccessControlDomains;
	}


	public void setLoginAccessControlDomains(SFAccessControlDomains loginaccesscontroldomains) {
		LoginAccessControlDomains = loginaccesscontroldomains;
	}


	public SFAccessControlDomains getFolderAccessControlDomains() {
		return FolderAccessControlDomains;
	}


	public void setFolderAccessControlDomains(SFAccessControlDomains folderaccesscontroldomains) {
		FolderAccessControlDomains = folderaccesscontroldomains;
	}


	public Integer getStorageQuotaPerUser() {
		return StorageQuotaPerUser;
	}


	public void setStorageQuotaPerUser(Integer storagequotaperuser) {
		StorageQuotaPerUser = storagequotaperuser;
	}


	public String getFreeTrialId() {
		return FreeTrialId;
	}


	public void setFreeTrialId(String freetrialid) {
		FreeTrialId = freetrialid;
	}


	public String getSource() {
		return Source;
	}


	public void setSource(String source) {
		Source = source;
	}


	public String getAttributedSource() {
		return AttributedSource;
	}


	public void setAttributedSource(String attributedsource) {
		AttributedSource = attributedsource;
	}


	public String getCompanyURL() {
		return CompanyURL;
	}


	public void setCompanyURL(String companyurl) {
		CompanyURL = companyurl;
	}


	public Boolean getMarketingOptIn() {
		return MarketingOptIn;
	}


	public void setMarketingOptIn(Boolean marketingoptin) {
		MarketingOptIn = marketingoptin;
	}


	public String getCreditCardSecurityCode() {
		return CreditCardSecurityCode;
	}


	public void setCreditCardSecurityCode(String creditcardsecuritycode) {
		CreditCardSecurityCode = creditcardsecuritycode;
	}


	public ArrayList<SFToolInformation> getToolInformation() {
		return ToolInformation;
	}


	public void setToolInformation(ArrayList<SFToolInformation> toolinformation) {
		ToolInformation = toolinformation;
	}

}