






// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------


package com.sharefile.api.models;

import com.google.gson.annotations.SerializedName;
import com.sharefile.api.enumerations.SFSafeEnum;


public class SFDeviceLogEntry extends SFODataObject {



	@SerializedName("FileName")

	private String FileName;


	@SerializedName("FileID")

	private String FileID;


	@SerializedName("Timestamp")

	private Long Timestamp;


	@SerializedName("AccountID")

	private String AccountID;


	@SerializedName("UserID")

	private String UserID;


	@SerializedName("Action")

	private SFSafeEnum<SFDeviceLogEntryAction> Action;


	@SerializedName("AdditionalInfo")

	private String AdditionalInfo;




		/**

		* File name

		*/

	public String getFileName() {
		return FileName;
	}


		/**

		* File name

		*/

	public void setFileName(String filename) {
		FileName = filename;
	}


	public String getFileID() {
		return FileID;
	}


	public void setFileID(String fileid) {
		FileID = fileid;
	}


	public Long getTimestamp() {
		return Timestamp;
	}


	public void setTimestamp(Long timestamp) {
		Timestamp = timestamp;
	}


	public String getAccountID() {
		return AccountID;
	}


	public void setAccountID(String accountid) {
		AccountID = accountid;
	}


	public String getUserID() {
		return UserID;
	}


	public void setUserID(String userid) {
		UserID = userid;
	}


	public SFSafeEnum<SFDeviceLogEntryAction> getAction() {
		return Action;
	}


	public void setAction(SFSafeEnum<SFDeviceLogEntryAction> action) {
		Action = action;
	}


	public String getAdditionalInfo() {
		return AdditionalInfo;
	}


	public void setAdditionalInfo(String additionalinfo) {
		AdditionalInfo = additionalinfo;
	}

}