
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
 
import com.google.gson.annotations.SerializedName;
import com.sharefile.api.enumerations.SFSafeEnum;

public class SFFindSubdomainResult extends SFODataObject {

	@SerializedName("UserID")
	private String UserID;
	@SerializedName("Email")
	private String Email;
	@SerializedName("AccountID")
	private String AccountID;
	@SerializedName("CompanyName")
	private String CompanyName;
	@SerializedName("Subdomain")
	private String Subdomain;

	public String getUserID() {
		return UserID;
	}

	public void setUserID(String userid) {
		UserID = userid;
	}
	public String getEmail() {
		return Email;
	}

	public void setEmail(String email) {
		Email = email;
	}
	public String getAccountID() {
		return AccountID;
	}

	public void setAccountID(String accountid) {
		AccountID = accountid;
	}
	public String getCompanyName() {
		return CompanyName;
	}

	public void setCompanyName(String companyname) {
		CompanyName = companyname;
	}
	public String getSubdomain() {
		return Subdomain;
	}

	public void setSubdomain(String subdomain) {
		Subdomain = subdomain;
	}
}