
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2015 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.sharefile.api.enumerations.SFSafeEnum;
import com.sharefile.api.models.*;

public class SFPowerTools extends SFODataObject {

	@SerializedName("EnableDesktopToolsPage")
	private Boolean EnableDesktopToolsPage;
	@SerializedName("EnableMobileApps")
	private Boolean EnableMobileApps;
	@SerializedName("ShowMobileTools")
	private Boolean ShowMobileTools;

	public Boolean getEnableDesktopToolsPage() {
		return this.EnableDesktopToolsPage;
	}

	public void setEnableDesktopToolsPage(Boolean enabledesktoptoolspage) {
		this.EnableDesktopToolsPage = enabledesktoptoolspage;
	}
	public Boolean getEnableMobileApps() {
		return this.EnableMobileApps;
	}

	public void setEnableMobileApps(Boolean enablemobileapps) {
		this.EnableMobileApps = enablemobileapps;
	}
	public Boolean getShowMobileTools() {
		return this.ShowMobileTools;
	}

	public void setShowMobileTools(Boolean showmobiletools) {
		this.ShowMobileTools = showmobiletools;
	}

}