






// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------


package com.sharefile.api.models;

import com.google.gson.annotations.SerializedName;


public class SFSimpleSearchQuery extends SFODataObject {



	@SerializedName("Query")

	private SFSimpleQuery Query;


	@SerializedName("Paging")

	private SFQueryPaging Paging;


	@SerializedName("Sort")

	private SFQuerySorting Sort;


	@SerializedName("TimeoutInSeconds")

	private Integer TimeoutInSeconds;




	public SFSimpleQuery getQuery() {
		return Query;
	}


	public void setQuery(SFSimpleQuery query) {
		Query = query;
	}


	public SFQueryPaging getPaging() {
		return Paging;
	}


	public void setPaging(SFQueryPaging paging) {
		Paging = paging;
	}


	public SFQuerySorting getSort() {
		return Sort;
	}


	public void setSort(SFQuerySorting sort) {
		Sort = sort;
	}


	public Integer getTimeoutInSeconds() {
		return TimeoutInSeconds;
	}


	public void setTimeoutInSeconds(Integer timeoutinseconds) {
		TimeoutInSeconds = timeoutinseconds;
	}

}