






// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------


package com.sharefile.api.models;

import java.util.ArrayList;

import com.google.gson.annotations.SerializedName;


public class SFSSOInfo extends SFODataObject {



	@SerializedName("Info")

	private ArrayList<SFSSOInfoEntry> Info;


	@SerializedName("AppControlPlane")

	private String AppControlPlane;


	@SerializedName("ApiControlPlane")

	private String ApiControlPlane;




	public ArrayList<SFSSOInfoEntry> getInfo() {
		return Info;
	}


	public void setInfo(ArrayList<SFSSOInfoEntry> info) {
		Info = info;
	}


	public String getAppControlPlane() {
		return AppControlPlane;
	}


	public void setAppControlPlane(String appcontrolplane) {
		AppControlPlane = appcontrolplane;
	}


	public String getApiControlPlane() {
		return ApiControlPlane;
	}


	public void setApiControlPlane(String apicontrolplane) {
		ApiControlPlane = apicontrolplane;
	}

}