
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;

import com.google.gson.annotations.SerializedName;
import com.sharefile.api.enumerations.SFSafeEnum;
import com.sharefile.api.models.*;

public class SFSSOAccountProvider extends SFODataObject {

	@SerializedName("LogoutUrl")
	private String LogoutUrl;
	@SerializedName("LoginUrl")
	private String LoginUrl;
	@SerializedName("IPRestrictions")
	private String IPRestrictions;
	@SerializedName("ForceSSO")
	private Boolean ForceSSO;
	@SerializedName("Certificate")
	private String Certificate;
	@SerializedName("Account")
	private SFAccount Account;
	@SerializedName("EntityID")
	private String EntityID;
	@SerializedName("SFEntityID")
	private String SFEntityID;
	@SerializedName("SPInitatedAuthContext")
	private String SPInitatedAuthContext;
	@SerializedName("SPInitatedAuthMethod")
	private String SPInitatedAuthMethod;
	@SerializedName("IsActive")
	private Boolean IsActive;
	@SerializedName("ProviderID")
	private String ProviderID;
	@SerializedName("DebugMode")
	private Boolean DebugMode;
	@SerializedName("LenientSignatures")
	private Boolean LenientSignatures;

	public String getLogoutUrl() {
		return LogoutUrl;
	}

	public void setLogoutUrl(String logouturl) {
		LogoutUrl = logouturl;
	}
	public String getLoginUrl() {
		return LoginUrl;
	}

	public void setLoginUrl(String loginurl) {
		LoginUrl = loginurl;
	}
	public String getIPRestrictions() {
		return IPRestrictions;
	}

	public void setIPRestrictions(String iprestrictions) {
		IPRestrictions = iprestrictions;
	}
	public Boolean getForceSSO() {
		return ForceSSO;
	}

	public void setForceSSO(Boolean forcesso) {
		ForceSSO = forcesso;
	}
	public String getCertificate() {
		return Certificate;
	}

	public void setCertificate(String certificate) {
		Certificate = certificate;
	}
	public SFAccount getAccount() {
		return Account;
	}

	public void setAccount(SFAccount account) {
		Account = account;
	}
	public String getEntityID() {
		return EntityID;
	}

	public void setEntityID(String entityid) {
		EntityID = entityid;
	}
	public String getSFEntityID() {
		return SFEntityID;
	}

	public void setSFEntityID(String sfentityid) {
		SFEntityID = sfentityid;
	}
	public String getSPInitatedAuthContext() {
		return SPInitatedAuthContext;
	}

	public void setSPInitatedAuthContext(String spinitatedauthcontext) {
		SPInitatedAuthContext = spinitatedauthcontext;
	}
	public String getSPInitatedAuthMethod() {
		return SPInitatedAuthMethod;
	}

	public void setSPInitatedAuthMethod(String spinitatedauthmethod) {
		SPInitatedAuthMethod = spinitatedauthmethod;
	}
	public Boolean getIsActive() {
		return IsActive;
	}

	public void setIsActive(Boolean isactive) {
		IsActive = isactive;
	}
	public String getProviderID() {
		return ProviderID;
	}

	public void setProviderID(String providerid) {
		ProviderID = providerid;
	}
	public Boolean getDebugMode() {
		return DebugMode;
	}

	public void setDebugMode(Boolean debugmode) {
		DebugMode = debugmode;
	}
	public Boolean getLenientSignatures() {
		return LenientSignatures;
	}

	public void setLenientSignatures(Boolean lenientsignatures) {
		LenientSignatures = lenientsignatures;
	}
}