
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
 
import com.google.gson.annotations.SerializedName;
import com.sharefile.api.enumerations.SFSafeEnum;

public enum SFUserRole {
	Client,
	Employee,
	MasterAdmin,
	SuperUser,
	CanChangePassword,
	CanManageMySettings,
	CanUseFileBox,
	CanManageUsers,
	CanCreateFolders,
	CanUseDropBox,
	CanSelectFolderZone,
	CreateNetworkShareConnectors,
	CreateSharePointConnectors,
	CreateSharePointOnlineConnectors,
	CreateOneDriveConnectors,
	CreateExchangeConnectors,
	CreateBoxConnectors,
	CreateDropboxConnectors,
	CreateGoogleDriveConnectors,
	AdminAccountPolicies,
	AdminBilling,
	AdminBranding,
	AdminChangeFolderPay,
	AdminChangePlan,
	AdminFileBoxAccess,
	AdminManageEmployees,
	AdminRemoteUploadForms,
	AdminReporting,
	AdminSharedDistGroups,
	AdminSharedAddressBook,
	AdminViewVdrAnalytics,
	AdminViewReceipts,
	AdminDelegate,
	AdminManageDropBox,
	AdminManageFolderTemplates,
	AdminEmailMessages,
	AdminSSO,
	AdminSuperGroup,
	AdminZones,
	AdminCreateSharedGroups,
	AdminArchivedSearch,
	AdminConnectors
}