
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

import java.io.InputStream;
import java.util.ArrayList;
import java.net.URI;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

import com.google.gson.annotations.SerializedName;
import com.sharefile.api.enumerations.SFSafeEnum;
import com.sharefile.api.models.*;

public class SFUserConfirmationSettings extends SFODataObject {

	@SerializedName("FirstName")
	private String FirstName;
	@SerializedName("LastName")
	private String LastName;
	@SerializedName("Company")
	private String Company;
	@SerializedName("Password")
	private String Password;
	@SerializedName("DayLightName")
	private String DayLightName;
	@SerializedName("UTCOffset")
	private String UTCOffset;
	@SerializedName("DateFormat")
	private String DateFormat;
	@SerializedName("TimeFormat")
	private String TimeFormat;
	@SerializedName("EmailInterval")
	private Integer EmailInterval;

	public String getFirstName() {
		return this.FirstName;
	}

	public void setFirstName(String firstname) {
		this.FirstName = firstname;
	}
	public String getLastName() {
		return this.LastName;
	}

	public void setLastName(String lastname) {
		this.LastName = lastname;
	}
	public String getCompany() {
		return this.Company;
	}

	public void setCompany(String company) {
		this.Company = company;
	}
	public String getPassword() {
		return this.Password;
	}

	public void setPassword(String password) {
		this.Password = password;
	}
	public String getDayLightName() {
		return this.DayLightName;
	}

	public void setDayLightName(String daylightname) {
		this.DayLightName = daylightname;
	}
	public String getUTCOffset() {
		return this.UTCOffset;
	}

	public void setUTCOffset(String utcoffset) {
		this.UTCOffset = utcoffset;
	}
	public String getDateFormat() {
		return this.DateFormat;
	}

	public void setDateFormat(String dateformat) {
		this.DateFormat = dateformat;
	}
	public String getTimeFormat() {
		return this.TimeFormat;
	}

	public void setTimeFormat(String timeformat) {
		this.TimeFormat = timeformat;
	}
	public Integer getEmailInterval() {
		return this.EmailInterval;
	}

	public void setEmailInterval(Integer emailinterval) {
		this.EmailInterval = emailinterval;
	}

}