
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

public class SFAccessControlsBulkParams extends SFODataObject {

	private Boolean mNotifyUser;
	private String mNotifyMessage;
	private ArrayList<SFAccessControlParam> mAccessControlParams;

		/**
		* Defines whether the principal should receieve a notice on the permission grant.
		* If an AccessControlParam doesn't specify the property it is inherited from here.
		*/
	public Boolean getNotifyUser() {
		return mNotifyUser;
	}

		/**
		* Defines whether the principal should receieve a notice on the permission grant.
		* If an AccessControlParam doesn't specify the property it is inherited from here.
		*/
	public void setNotifyUser(Boolean notifyuser) {
		mNotifyUser = notifyuser;
	}
		/**
		* Custom notification message, if any
		* If an AccessControlParam doesn't specify the property it is inherited from here.
		*/
	public String getNotifyMessage() {
		return mNotifyMessage;
	}

		/**
		* Custom notification message, if any
		* If an AccessControlParam doesn't specify the property it is inherited from here.
		*/
	public void setNotifyMessage(String notifymessage) {
		mNotifyMessage = notifymessage;
	}
		/**
		* AccessControlParams
		*/
	public ArrayList<SFAccessControlParam> getAccessControlParams() {
		return mAccessControlParams;
	}

		/**
		* AccessControlParams
		*/
	public void setAccessControlParams(ArrayList<SFAccessControlParam> accesscontrolparams) {
		mAccessControlParams = accesscontrolparams;
	}
}