
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

public class SFEnsSubscriberConfiguration extends SFODataObject {

	private Boolean mIsEnsEnabled;
	private String mEnsServerUrl;
	private String mVersion;
	private Object mRecommendedPollingSyncInterval;
	private Object mRecommendedNotificationSyncInterval;
	private Integer mNotificationConfigurationCount;
	private Integer mFailSafePollingCount;
	private Integer mMaxNotificationSyncWaitCount;

	public Boolean getIsEnsEnabled() {
		return mIsEnsEnabled;
	}

	public void setIsEnsEnabled(Boolean isensenabled) {
		mIsEnsEnabled = isensenabled;
	}
	public String getEnsServerUrl() {
		return mEnsServerUrl;
	}

	public void setEnsServerUrl(String ensserverurl) {
		mEnsServerUrl = ensserverurl;
	}
	public String getVersion() {
		return mVersion;
	}

	public void setVersion(String version) {
		mVersion = version;
	}
	public Object getRecommendedPollingSyncInterval() {
		return mRecommendedPollingSyncInterval;
	}

	public void setRecommendedPollingSyncInterval(Object recommendedpollingsyncinterval) {
		mRecommendedPollingSyncInterval = recommendedpollingsyncinterval;
	}
	public Object getRecommendedNotificationSyncInterval() {
		return mRecommendedNotificationSyncInterval;
	}

	public void setRecommendedNotificationSyncInterval(Object recommendednotificationsyncinterval) {
		mRecommendedNotificationSyncInterval = recommendednotificationsyncinterval;
	}
	public Integer getNotificationConfigurationCount() {
		return mNotificationConfigurationCount;
	}

	public void setNotificationConfigurationCount(Integer notificationconfigurationcount) {
		mNotificationConfigurationCount = notificationconfigurationcount;
	}
	public Integer getFailSafePollingCount() {
		return mFailSafePollingCount;
	}

	public void setFailSafePollingCount(Integer failsafepollingcount) {
		mFailSafePollingCount = failsafepollingcount;
	}
	public Integer getMaxNotificationSyncWaitCount() {
		return mMaxNotificationSyncWaitCount;
	}

	public void setMaxNotificationSyncWaitCount(Integer maxnotificationsyncwaitcount) {
		mMaxNotificationSyncWaitCount = maxnotificationsyncwaitcount;
	}
}