
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

public class SFEnsSubscriptionToken extends SFODataObject {

	private String mSubscriptionId;
	private String mEntityId;
	private SFSafeEnum<SFEnsEventType> mEventTypes;
	private Boolean mIncludeProgeny;

	public String getSubscriptionId() {
		return mSubscriptionId;
	}

	public void setSubscriptionId(String subscriptionid) {
		mSubscriptionId = subscriptionid;
	}
	public String getEntityId() {
		return mEntityId;
	}

	public void setEntityId(String entityid) {
		mEntityId = entityid;
	}
	public SFSafeEnum<SFEnsEventType> getEventTypes() {
		return mEventTypes;
	}

	public void setEventTypes(SFSafeEnum<SFEnsEventType> eventtypes) {
		mEventTypes = eventtypes;
	}
	public Boolean getIncludeProgeny() {
		return mIncludeProgeny;
	}

	public void setIncludeProgeny(Boolean includeprogeny) {
		mIncludeProgeny = includeprogeny;
	}
}