
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2014 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.sharefile.api.models;

public class SFFreeTrialAccount extends SFAccount {

	private String mPromoCode;
	private Date mEndDate;
	private Boolean mIsValid;
	private String mConversionType;
	private Boolean mHasFollowedUp;
	private Date mFollowUpDate;
	private String mCancellationReason;
	private String mSignupProcess;
	private Double mConversionIndexDay7;
	private Double mConversionIndexDay14;
	private Double mLTVIndex;
	private String mAllSources;
	private String mReferralID;
	private Integer mTrialTypeID;
	private String mInitialCallRepID;
	private Date mInitialCallDate;
	private Integer mDemoStatus;
	private Date mDemoDate;
	private String mMarketoID;

	public String getPromoCode() {
		return mPromoCode;
	}

	public void setPromoCode(String promocode) {
		mPromoCode = promocode;
	}
	public Date getEndDate() {
		return mEndDate;
	}

	public void setEndDate(Date enddate) {
		mEndDate = enddate;
	}
	public Boolean getIsValid() {
		return mIsValid;
	}

	public void setIsValid(Boolean isvalid) {
		mIsValid = isvalid;
	}
	public String getConversionType() {
		return mConversionType;
	}

	public void setConversionType(String conversiontype) {
		mConversionType = conversiontype;
	}
	public Boolean getHasFollowedUp() {
		return mHasFollowedUp;
	}

	public void setHasFollowedUp(Boolean hasfollowedup) {
		mHasFollowedUp = hasfollowedup;
	}
	public Date getFollowUpDate() {
		return mFollowUpDate;
	}

	public void setFollowUpDate(Date followupdate) {
		mFollowUpDate = followupdate;
	}
	public String getCancellationReason() {
		return mCancellationReason;
	}

	public void setCancellationReason(String cancellationreason) {
		mCancellationReason = cancellationreason;
	}
	public String getSignupProcess() {
		return mSignupProcess;
	}

	public void setSignupProcess(String signupprocess) {
		mSignupProcess = signupprocess;
	}
	public Double getConversionIndexDay7() {
		return mConversionIndexDay7;
	}

	public void setConversionIndexDay7(Double conversionindexday7) {
		mConversionIndexDay7 = conversionindexday7;
	}
	public Double getConversionIndexDay14() {
		return mConversionIndexDay14;
	}

	public void setConversionIndexDay14(Double conversionindexday14) {
		mConversionIndexDay14 = conversionindexday14;
	}
	public Double getLTVIndex() {
		return mLTVIndex;
	}

	public void setLTVIndex(Double ltvindex) {
		mLTVIndex = ltvindex;
	}
	public String getAllSources() {
		return mAllSources;
	}

	public void setAllSources(String allsources) {
		mAllSources = allsources;
	}
	public String getReferralID() {
		return mReferralID;
	}

	public void setReferralID(String referralid) {
		mReferralID = referralid;
	}
	public Integer getTrialTypeID() {
		return mTrialTypeID;
	}

	public void setTrialTypeID(Integer trialtypeid) {
		mTrialTypeID = trialtypeid;
	}
	public String getInitialCallRepID() {
		return mInitialCallRepID;
	}

	public void setInitialCallRepID(String initialcallrepid) {
		mInitialCallRepID = initialcallrepid;
	}
	public Date getInitialCallDate() {
		return mInitialCallDate;
	}

	public void setInitialCallDate(Date initialcalldate) {
		mInitialCallDate = initialcalldate;
	}
	public Integer getDemoStatus() {
		return mDemoStatus;
	}

	public void setDemoStatus(Integer demostatus) {
		mDemoStatus = demostatus;
	}
	public Date getDemoDate() {
		return mDemoDate;
	}

	public void setDemoDate(Date demodate) {
		mDemoDate = demodate;
	}
	public String getMarketoID() {
		return mMarketoID;
	}

	public void setMarketoID(String marketoid) {
		mMarketoID = marketoid;
	}
}